// CASE No. 003 — "Dead Air"
window.CASES = window.CASES || [];
window.CASES.push({
  id: "deadair",
  fileNo: "003",
  title: "Dead Air",
  tagline: "Sixty seconds of silence, broadcast live. He never spoke again.",
  place: "Radio Station WQXT, Meridian City",
  date: "March 8th, 1947",
  difficulty: 3,
  startMinutes: 0 * 60 + 20, // 12:20 AM
  timeBudget: 360,           // DA at 6:20 AM
  deadlineLabel: "The District Attorney arrives at 6:20 AM to take over — and he owed the victim favors. Solve it before the case becomes a eulogy.",
  epigraph: "“Radio is the only place where silence has a schedule. Someone read the schedule very carefully.”",
  briefing: [
    "Every Friday at midnight, half the county tunes to WQXT for 'The Midnight Hour' — Walter Herrick's true-crime program, the show that made him famous twenty years ago when it named the Orchard Farm killer on the air.",
    "Every episode ends the same way: sixty seconds of dead air, 'for the victims,' while Herrick grips the microphone and stares down the studio clock. Showmanship. Trademark. Ritual.",
    "Tonight at 12:03, eleven seconds into the silence, the studio lights dipped, Herrick convulsed, and four thousand listeners heard a man die without a word being spoken. The microphone was live with something other than his voice.",
    "The engineer found the mic's ground wire cut and the line cross-patched to plate voltage — a trap, set hours earlier, that needed one final switch thrown to kill. The station doors were locked at five. Whoever built this is still in the building, and they understand electricity, timing, and patience.",
  ],
  detectiveNote: "The trap was built early but sprung at 12:03 exactly — during the one minute nobody would be speaking or touching equipment. Ask who controls that minute.",

  locations: [
    {
      id: "studioA", name: "Studio A", col: 2, row: 1,
      desc: "The murder room: cork walls, a dead ON AIR sign, and Herrick's chair pushed back from the table where he fell. The microphone — a big ribbon mic on a scorched stand — has been unplugged and roped off. Through the double glass, the control room watches like an aquarium.",
      hotspots: [
        { id: "h_mic", name: "The microphone",
          found: "Scorch shadows up the grille, and on the underside of the stand a ground strap cut clean — snipped, not frayed, the copper still bright. With the ground cut and the line hot, the first firm grip completes the circuit. Herrick gripped this mic the same way at the same minute every Friday for twenty years. His ritual was the trigger.",
          gives: ["c3_mic"] },
        { id: "h_script", name: "Herrick's script",
          found: "Tonight's script, and clipped behind it, notes for next week in Herrick's red pencil: 'EP. 400 — THE ORCHARD FARM CASE, REVISITED. The one that made us. Pull the '27 discs, replay the confession, the arrest, the verdict. PLAY IT PROUD.' Episode 400 would have re-aired his most famous hour — the night his broadcast put a man behind bars.",
          gives: ["c3_script"] },
        { id: "h_cup", name: "The coffee cup",
          found: "Black coffee, gone cold, untouched — you have it sniffed and later tested: it's only coffee. Whoever killed Walter Herrick considered the obvious methods and declined them. Poison is uncertain. Electricity, on a man with a famous grip and a famous schedule, is punctual.",
          gives: ["c3_coffee"] },
      ],
    },
    {
      id: "control", name: "The Control Room", col: 3, row: 1,
      desc: "The other side of the glass: the mixing board with its rows of Bakelite knobs, the cue-sheet clipboard, two turntables still spinning silently. Dorothy 'Dot' Lange, the producer, sits where she sat when he died — very upright, very pale, watching the empty studio the way people watch the sea.",
      hotspots: [
        { id: "h_patchbay", name: "The patch bay",
          found: "Behind the board, a wall of jacks and cords — the station's nervous system. One patch is wrong: the Studio A mic line crossed to the transmitter's plate-voltage feed through a spare jack. Rigged this way, the line stays harmless while the channel is muted — and turns lethal the moment the board operator opens the studio mic. The trap didn't fire on a timer. Someone at this board chose the second.",
          gives: ["c3_patch"] },
        { id: "h_cuesheet", name: "The cue sheet",
          found: "The broadcast log, timed to the second in the producer's neat hand. 11:58:30 — Herrick, closing remarks. 12:02:49 — 'DEAD AIR — 60 SEC — ALL MICS OPEN, STUDIO SILENT.' All mics open. During the silence, the board's channels are unmuted so the 'living silence' of the room goes out over the air. Herrick's own ritual required his mic to be made live at 12:03 — and the whole staff has known it for years.",
          gives: ["c3_cuesheet"] },
      ],
    },
    {
      id: "shop", name: "The Engineering Shop", col: 3, row: 2,
      desc: "Eugene Pratt's kingdom of solder and spare tubes, orderly as a surgery. Every tool hangs on a shadow board — a painted outline for each. One outline is empty.",
      hotspots: [
        { id: "h_toolwall", name: "The shadow board",
          found: "One empty outline: the small wire cutters, the pair Pratt calls his 'close-work nips.' He noticed them missing when he came back from dinner at seven and logged it — engineers log everything. Cut ground strap in Studio A, missing cutters in the shop. The tool went for a walk between six and seven.",
          gives: ["c3_tools"] },
        { id: "h_keylog", name: "The key sign-out sheet",
          found: "The master-key log, kept by the shop door. 'CONTROL ROOM + STUDIO A — SIGNED OUT 6:15 PM — E. PRATT.' But Pratt signs his name like a cardiogram, all spikes — you've seen it three lines up. This 6:15 entry is rounded, careful, wrong. Someone took the master key during the dinner hour and signed the engineer's name to the borrowing.",
          gives: ["c3_keylog"] },
        { id: "h_schematics", name: "The transformer schematics",
          found: "Station wiring diagrams on the bench, the binder's spine cracked open to one page: 'GROUNDING FAULTS — PLATE SUPPLY HAZARDS,' the page that explains, with a diagram, exactly how tonight's trap works. The corner is dog-eared by a thumb that came back to it more than once. Pratt wrote these diagrams — he'd never need to study them. Someone else did.",
          gives: ["c3_schematic"] },
      ],
    },
    {
      id: "effects", name: "The Effects Room", col: 1, row: 1,
      desc: "The sound-effects library: a door that slams in a frame, a thunder sheet, gravel boxes, coconut shells, and the Hammond organ where Iris Bell scores the nightmares of 'The Midnight Hour.' Iris sits at the organ bench, hands in her lap, not playing.",
      hotspots: [
        { id: "h_thunder", name: "The thunder-sheet crate",
          found: "Down among the felt and rope handles: a pair of small wire cutters, copper-bright at the jaws from a recent cut. The engineer's missing 'close-work nips,' hidden in a crate nobody opens unless the script calls for a storm. Tonight's script called for no storms — the killer knew that too.",
          gives: ["c3_cutters"] },
        { id: "h_organ", name: "The organ bench",
          found: "Inside the bench, sheet music and Iris's pocket diary. Tonight's entry, written before midnight in a happy hand: 'Dinner w/ Gene, Milt's Diner, 6–7. He talked circuits the whole hour, bless him. Split the pie.' Milt's is three blocks off. A counter man and a pie can be checked, and you have it checked: confirmed. Iris and Eugene were out of the building six to seven.",
          gives: ["c3_dinner"] },
      ],
    },
    {
      id: "office", name: "Herrick's Office", col: 2, row: 2,
      desc: "The dead man's office, all trophies: framed clippings, a key to the city, twenty years of 'The Midnight Hour' bound in leather. The room of a man who solved one great case and never stopped billing it.",
      hotspots: [
        { id: "h_casefile", name: "The Orchard Farm file",
          found: "His private file on the case that made him. 1927: the Orchard Farm murders; Herrick's broadcast names Ray Lundgren, an itinerant picker, on the air — three days before the trial. Conviction. Life sentence. Clipped at the back, a wire item from 1939, four lines: 'ORCHARD FARM SLAYER DIES IN PRISON. Raymond Lundgren, 44, maintained his innocence to the last.' And under it, in Herrick's red pencil, one word: 'FINALLY.'",
          gives: ["c3_orchard"] },
        { id: "h_letters", name: "The correspondence drawer",
          found: "Fan mail, station business — and one letter apart from the rest, worn soft from handling, dated 1940: 'My father died in your prison last spring still swearing what I have always known. You did not investigate, Mr. Herrick. You performed. Someday somebody will perform for you. — D.L.' He kept it seven years. Maybe he thought it was a trophy too.",
          gives: ["c3_letter"] },
        { id: "h_contracts", name: "The contracts drawer",
          found: "Two documents, both fresh: a letter from Vellum Cigarettes canceling their sponsorship over 'programming disagreements' — and a signed memo, effective yesterday, terminating Chet Morrow's afternoon program. 'Nothing personal, Chet. Arithmetic. — W.H.' In this building, the dead man had spent the week making enemies at a rate even he couldn't sustain.",
          gives: ["c3_sponsor", "c3_memo"] },
      ],
    },
    {
      id: "lobby", name: "The Front Office", col: 1, row: 2,
      desc: "Reception: a switchboard, a visitor book, filing cabinets of personnel records. Chet Morrow paces a groove in the linoleum. Sam Ostrow of Vellum Cigarettes sits with his hat on his knee like a man waiting for a train that's already been derailed.",
      hotspots: [
        { id: "h_visitorbook", name: "The visitor book",
          found: "The receptionist's book, kept until she left at five, when the doors were locked: no visitors after 4:40, all keys accounted for at the front desk, night staff only in the building. Six people were inside WQXT when Walter Herrick died, and you have spoken to five of them and stood over the sixth. This is the whole cast.",
          gives: ["c3_visitors"] },
        { id: "h_chetdesk", name: "Chet Morrow's cleared desk",
          found: "A cardboard box of a canceled career: coffee mug, publicity stills, and — crumpled in the wastebasket beside it — a note drafted and abandoned in an angry hand: 'You'll regret this, Walter. Fifteen years and you hand me arithmetic. You'll regret—' It ends there. Men who mean it usually finish the sentence. Men who mean it usually don't leave it in the wastebasket, either.",
          gives: ["c3_note"] },
        { id: "h_personnel", name: "The personnel files", requiresClue: "c3_letter",
          lockedHint: "A wall of staff files. You'd be fishing without a name to look for — though those initials from the office, 'D.L.', keep circling your head.",
          found: "D.L. You pull the file: LANGE, DOROTHY — hired 1941, references from out of state, exemplary record. But on her original application, under the lamp, the typed surname sits on a bed of correction fluid. You hold it to the light and the ghost letters rise through: L-U-N-D-G-R-E-N. Dorothy Lundgren. The letter-writer. The daughter. She has sat six feet from Walter Herrick, on the other side of the glass, for six years.",
          gives: ["c3_personnel"] },
      ],
    },
  ],

  suspects: [
    {
      id: "dot", name: "Dorothy 'Dot' Lange", role: "The producer", age: 31,
      color: "#5e4353", initials: "DL", location: "control",
      blurb: "Six years producing 'The Midnight Hour' — the quiet perfectionist who runs the board, times the show to the second, and made Herrick's ritual run like a Swiss watch. She was at the controls, behind glass, when he died. The one person visibly nowhere near him.",
      topics: [
        { id: "t_d_account", label: "Her account of 12:03",
          response: "“At 12:02:49 I opened the studio channels for the silence, the way I have four hundred times. At 12:03:00 the clock hit the top and he took the microphone — he always took the microphone, both hands, like a man gripping a rail. At :11 the lights dipped and he stood up halfway and then he didn't stand up any more.” Her voice is level as a cue sheet. “I cut the feed at :19 and called the operator at :40. You may check my times. My times are always right.”",
          note: "Her account is timed to the second — she opened the mics at 12:02:49, per the ritual. Cool as a cue sheet, and knows it." },
        { id: "t_d_board", label: "Who runs the board?",
          response: "“I do. It's a producer's board — Gene built it, but on air it's mine. Nobody else touched it tonight.” You ask who else COULD run it. “Gene, of course. Iris knows enough to fade her own organ. Walter never learned a knob of it — talent doesn't, as a rule.” She looks through the glass at the roped-off microphone. “You're asking who could have opened his channel at 12:03. The answer is me, Inspector. The answer is only me. I'd rather you heard it from my mouth than from the wiring.”",
          gives: ["c3_boardaccess"],
          note: "Volunteers, unprompted, that only she could have opened the fatal channel at 12:03. Either innocence — or control of the narrative." },
        { id: "t_d_herrick", label: "About Herrick",
          response: "“Walter was the best broadcaster I ever heard and the laziest investigator. The files did not matter to him; the SOUND of certainty mattered.” A beat too honest, and she knows it. “You produce a man six years, you learn where the paint is thin. I kept his show perfect. What I thought of him was not on the air.”",
          note: "'The sound of certainty mattered' — six years of contempt, precisely rationed." },
        { id: "t_d_keylog", label: "Present the forged key log", requiresClue: "c3_keylog", confront: true,
          response: "She studies the forged signature with what looks like professional interest. “That's not Gene's hand. Gene writes like a seismograph.” Whose is it, then? “Someone patient enough to practice roundness. Half this staff could have taken that key at dinner hour, Inspector — the shop stands open, the desk stands empty.” She hands the sheet back, steady. Steady like her cue times. You notice she never asked what the key was used FOR — and everyone else in this building asked you that within the first minute.",
          gives: ["c3_neverasked"],
          note: "Analyzed the forgery calmly — and never once asked what the master key had been used to do. Everyone else asked." },
        { id: "t_d_father", label: "Present the personnel file", requiresClue: "c3_personnel", confront: true,
          response: "The stillness stops being calm and becomes something older, practiced deeper. “Lundgren,” she says, and saying it seems to cost twenty years. “My father picked fruit and fixed radios — he taught me circuits before I could write. In 1927, Walter Herrick needed an ending for his broadcast, and my father was camped in the wrong orchard with a knife every picker carries.” She folds her hands, cue-sheet neat. “I changed my name because no one hires a Lundgren in this state. I took this job because— you may finish that sentence however you like, Inspector. You will anyway.” She does not deny. She waits — like a woman watching a clock run down.",
          gives: ["c3_admitname"],
          note: "Admits she is Dorothy Lundgren — the condemned man's daughter, hired under a corrected name, six feet of glass from Herrick for six years. Admits nothing further. Waits." },
        { id: "t_d_break", label: "Read her the whole timeline", requiresDeductions: ["d3_board", "d3_daughter"], confront: true, climax: true,
          response: "You read it to her like a cue sheet, because it is one. 6:02 — the building empties for dinner; she alone remains. 6:15 — the master key signed out under a practiced, rounded forgery. The dog-eared grounding-fault page in a binder its own author would never need. The snipped ground strap. The cross-patch only the board could arm. 12:02:49 — all mics open. 12:03:11 — done. She listens the way she listens to airchecks — for errors. She finds none.\n\n“Twenty years ago, Walter Herrick ended a broadcast by pointing at my father,” she says at last. “Three days of 'investigation.' He needed the ending before the weekend, you see. Papa wrote me every month for twelve years — circuit diagrams in the margins, so I'd keep learning. In 1939 the letters stopped, and Herrick's red pencil wrote 'FINALLY' in a file, and I have read that word every time I have dusted that office for six years.”\n\nThrough the glass, the roped-off microphone. “I was going to let him live, Inspector. Hating a man to his face across a mixing board is almost enough — almost. Then Tuesday he handed me the notes for Episode 400. 'The one that made us. Play it proud.' He was going to replay my father's destruction as an anniversary special, with organ music. I timed the show for him one last time instead.” She straightens the cue sheet on the desk, a small, final, professional gesture. “He always said silence was the most powerful thing on radio. I gave him sixty seconds of it. He only needed eleven.”",
          gives: ["c3_confession"],
          note: "CONFESSED. She built the trap during the dinner hour and sprang it from the board at 12:03 — vengeance for her father, detonated by Herrick's plan to replay the Orchard Farm 'triumph' as Episode 400." },
      ],
    },
    {
      id: "eugene", name: "Eugene Pratt", role: "The chief engineer", age: 45,
      color: "#47536e", initials: "EP", location: "shop",
      blurb: "Twenty years keeping WQXT on the air; the trap in the patch bay is textbook Pratt work — which he'd tell you himself, glumly. The only staffer who could rig it blindfolded, and he knows exactly how that arithmetic looks.",
      topics: [
        { id: "t_e_technical", label: "Explain the trap",
          response: "He walks you through it with chalk on the shop's slate, miserable and precise. “Ground strap cut at the stand — that's the return path gone. Mic line cross-patched to the plate feed — that's six hundred volts waiting on a closed circuit. Harmless while the channel's muted. The instant the board opens that channel—” he claps chalk dust off his hands, flinching at his own gesture. “Whoever did this knew our wiring or studied it hard. It's not a lucky accident. It's a design.”",
          gives: ["c3_expertread"],
          note: "Confirms the mechanism: the trap stayed inert until the BOARD opened the studio channel. The board operator's unmute was the trigger." },
        { id: "t_e_dinner", label: "His whereabouts, six to seven",
          response: "“Milt's Diner with Iris, quarter past six to just past seven — corner booth, blue-plate special, I bored the poor woman rigid about impedance matching, and Milt will remember because I short-changed him a nickel and went back with it.” He rubs his neck. “I know how this reads, Inspector. It's my wiring, my patch bay, my kind of work. If I'd wanted an alibi I'd have built a better one than a plate of meatloaf.” The diner checks out — counter man, booth, nickel and all.",
          note: "Airtight: at Milt's Diner with Iris, 6:15–7:05, confirmed independently. The trap was set during the very hour he was demonstrably eating meatloaf." },
        { id: "t_e_keylog", label: "Present the forged key log", requiresClue: "c3_keylog", confront: true,
          response: "He stares at the signature and goes a slow, dangerous red. “That is not my hand. I sign like— everyone jokes about how I sign.” He fetches the log's earlier pages and lays them side by side: spikes against curves, a lightning storm against a lullaby. “Somebody borrowed my name to borrow my key while I ate meatloaf three blocks away.” Quietly furious now: “And they gave it back, Inspector. Key was on its hook at eight. They used my shop, my tools, my name, and they were TIDY about it.”",
          gives: ["c3_forgery"],
          note: "Side-by-side comparison proves the 6:15 signature is forged. The key was returned to its hook by eight — the killer is tidy, patient, internal." },
        { id: "t_e_students", label: "Who has he taught wiring?",
          response: "An unhappy pause. “Iris knows her organ pickups and no more. Chet can't wire a plug. Ostrow's a sponsor; sponsors touch nothing but their hats.” Longer pause. “Dot.” He says it reluctantly, like tearing tape off skin. “Six years of Friday nights, she's sat with me through every breakdown — asks good questions, the right questions. Last fall she borrowed my grounding schematics for a week. Said if the show ever went down on air, she wanted to understand what she was looking at.” He hears it as he says it. “She said UNDERSTAND. I remember being pleased.”",
          gives: ["c3_student"],
          note: "Dot has absorbed six years of his troubleshooting — and borrowed the grounding schematics last fall 'to understand what she was looking at.'" },
      ],
    },
    {
      id: "iris", name: "Iris Bell", role: "The effects artist", age: 38,
      color: "#5d6b42", initials: "IB", location: "effects",
      blurb: "Ten years of thunder sheets and Hammond dread — the sound of 'The Midnight Hour' is mostly her hands. Sharp-eyed, warm, and worried about someone, which is the most interesting thing in the room.",
      topics: [
        { id: "t_i_alibi", label: "Her whereabouts tonight",
          response: "“Dinner with Gene at Milt's, six to seven — he talked circuits, I ate his pickles, it's our arrangement. Then here till air time, then in the effects booth for the broadcast.” Her hands demonstrate on phantom equipment. “At 12:03 I do nothing — the silence needs no effects, God knows. I heard him die through my cans, Inspector. Sixty cycles of hum where a man's breathing should be. I'll hear it the rest of my life.”",
          note: "With Eugene at Milt's during the trap-setting hour; in the effects booth on air. Heard the electrical hum through her headphones at 12:03." },
        { id: "t_i_cutters", label: "Present the wire cutters", requiresClue: "c3_cutters", confront: true,
          response: "“In my thunder crate?” Genuine shock, then fast thinking — you watch her run the same logic you did. “Nobody opens that crate without a storm in the script, and there's no storm till the Easter show. Whoever hid those knew our scripts.” Then her face does something complicated and she shuts it down. “That's— it's a prop room, Inspector. Anyone can walk in.” She's just thought of someone specific. She's decided not to say who.",
          note: "The hiding place required knowing the effects schedule weeks out. She thought of a name and locked it behind her teeth." },
        { id: "t_i_staff", label: "The people of WQXT",
          response: "“Walter was the show, and knew it, and priced it. Chet's a wounded rooster — loud grief, no talons. Ostrow's arithmetic in a hat. Gene is the gentlest soul in broadcasting.” And the producer? Iris's warmth banks itself, careful as a fader. “Dot is the best professional I've ever shared a wall with. Six years, never late, never wrong, never—” she looks for the word and picks it deliberately, “—never OFF the clock. You've met people like that? Where the clock is doing something for them?”",
          gives: ["c3_irisdoubt"],
          note: "On Dot: 'never off the clock — where the clock is doing something for them.' Iris suspects; Iris won't say it plainer." },
        { id: "t_i_january", label: "What she's not saying", requiresClue: "c3_admitname",
          response: "You tell her you know about the name in the personnel file. The banked fire goes out; what's left is sadness. “Then I'll say the rest of it. In January I came back for my gloves, near midnight, and the aircheck room was running. Dot was at the machine playing an old disc — 1927 label — over and over. A man's voice, frightened, saying he'd never been inside the farmhouse. And Dot just sitting there in the dark with her cue watch in her hand, timing it. Timing HIM.” Iris's eyes are wet. “I told myself it was research. We tell ourselves things in this business — we're professionals at it. You didn't hear this from me, Inspector, except that you did, and God forgive us both.”",
          gives: ["c3_aircheck"],
          note: "January, near midnight: Dot alone in the dark, replaying the 1927 Lundgren broadcast over and over — timing it with her cue watch." },
      ],
    },
    {
      id: "chet", name: "Chet Morrow", role: "The fired afternoon host", age: 51,
      color: "#7a5e2c", initials: "CM", location: "lobby",
      blurb: "Fifteen years of the two-o'clock slot, terminated by memo yesterday. Loud, wounded, and still in the building at midnight, which he'll need to explain. The obvious suspect — which, in your experience, is a job description rarely filled.",
      topics: [
        { id: "t_c_why", label: "Why is he here at midnight?",
          response: "“Because I've got fifteen years in that desk and one cardboard box to show for it, and I wanted to clear it out with nobody watching, all right? A man's allowed to bury himself in private.” He glares, daring you to laugh. “I was at my desk when the lights dipped. Ostrow was sitting right there waiting to ambush Walter after the show — ask him. We alibi each other, which I know is worth what it's worth, seeing as we both wanted to skin the man.”",
          gives: ["c3_lobbyalibi"],
          note: "Clearing his desk in the lobby at 12:03 — he and Ostrow in each other's sight. Two men with motives, alibiing each other." },
        { id: "t_c_note", label: "Present the crumpled note", requiresClue: "c3_note", confront: true,
          response: "He goes purple, then deflates like a leaving train. “Wrote it at four, crumpled it at five past. What was I going to threaten him with, my ratings?” A bitter laugh. “Here's the thing you should chew on, Inspector: I wanted him ruined, not dead. Dead, he's a legend — they'll rename the studio for him. RUINED was the project. I've been calling wire services all week about the Orchard Farm case. There's a stringer in the capital says the state's had a re-examination petition rotting in a drawer since '39. THAT was my knife. Some vulture's beaten me to the man with a worse one.”",
          gives: ["c3_petition"],
          note: "His revenge was exposure, not murder — he'd been shopping the Orchard Farm re-examination petition to wire services all week. The old case was already surfacing." },
        { id: "t_c_herrick", label: "Fifteen years of Herrick",
          response: "“Walter Herrick never investigated a thing in his life; he NARRATED. Difference is, investigations end when the facts do — narrations end at the top of the hour.” He jabs a finger toward the office of trophies. “The Orchard Farm show? He had the script written before the arrest, ask anyone from the old days. The picker fit the airtime, so the picker hanged— well. Died inside, same thing, slower.” He catches himself being honest and scowls. “I hated him fair and in daylight, Inspector. Whoever did this hated him in the dark, on a schedule. That's not my breed of hate.”",
          note: "'The script was written before the arrest.' Even Herrick's enemies knew the 1927 case was theatre. And: 'whoever did this hated on a schedule.'" },
      ],
    },
    {
      id: "ostrow", name: "Sam Ostrow", role: "The sponsor's man", age: 48,
      color: "#6d5138", initials: "SO", location: "lobby",
      blurb: "Vellum Cigarettes' account man, sent to cancel the sponsorship in person, hat on knee, waiting out a dead man's last broadcast. A creature of contracts and column inches — and possibly the only person in the building with no history here at all.",
      topics: [
        { id: "t_o_business", label: "Why cancel the sponsorship?",
          response: "“Nothing mysterious, Inspector — arithmetic with a letterhead. Herrick wanted a raise; the numbers wanted a rest. I came at eleven to deliver it in person after the show, because Walter took bad news better with an audience of one.” He shrugs, hat steady on the knee. “A dead host is not a business outcome anyone at Vellum drew up. Sponsors don't kill programs. We cancel them. It's cleaner and legal.”",
          note: "In the building since eleven to cancel the contract face-to-face after the show. Motive-shaped, but the motive runs backward — his job was paperwork, not corpses." },
        { id: "t_o_lobby", label: "What he saw from the lobby",
          response: "“I sat in that chair from eleven o'clock, and I notice things; noticing is the job.” He inventories the evening like a media buy. “The fired fellow, Morrow, at his desk the whole time, banging drawers. The organist crossed to the effects room at half eleven. The engineer to his shop about the same. Herrick to the studio at quarter to. And the producer—” the hat rotates once on the knee, “—the producer I saw at six, when I first came by to leave my card. Building was empty for dinner, but she was here. Coming up the hall from the shop wing, walking fast, wiping her hands on a handkerchief. She told me the station was closed and to come back at eleven. Very composed. Very— rehearsed, if you want the word from a man who writes ad copy.”",
          gives: ["c3_sixoclock"],
          note: "CRUCIAL: at 6 PM, in the emptied building, he saw Dot coming FROM THE SHOP WING, fast, wiping her hands — hours before she claims her evening began." },
        { id: "t_o_herrick", label: "Herrick as an account",
          response: "“Twenty years, the man sold certainty at midnight. Wonderful voice, terrible margins.” He allows himself one human sentence: “I've canceled forty programs, Inspector. This is the first time the program canceled the host first. Vellum will not be sponsoring the funeral, but I'll be attending. Radio men go, at the end, whatever we thought of the arithmetic.”",
          note: "No history with Herrick beyond the ledger. His timeline observations are a media buyer's — precise and disinterested." },
      ],
    },
  ],

  clues: {
    c3_mic:       { name: "The Rigged Microphone", desc: "Ground strap snipped clean under the stand. The first firm grip completes the circuit — and Herrick's two-handed grip at 12:03 was twenty years of ritual." },
    c3_script:    { name: "Episode 400 Notes", desc: "Herrick's plan for next week: replay the 1927 Orchard Farm broadcast — 'the one that made us. PLAY IT PROUD.'" },
    c3_coffee:    { name: "The Untouched Coffee", desc: "Tested: only coffee. The killer declined poison. Electricity, on a man with a famous grip and famous schedule, is punctual." },
    c3_patch:     { name: "The Cross-Patch", desc: "Mic line jumped to plate voltage through the patch bay — inert while muted, lethal the instant the board opens the channel. The trap's trigger was the board itself." },
    c3_cuesheet:  { name: "The Cue Sheet", desc: "12:02:49 — 'DEAD AIR, 60 SEC, ALL MICS OPEN.' The ritual required the fatal channel to be opened at that second. The whole staff knew." },
    c3_tools:     { name: "The Empty Shadow Board", desc: "The engineer's close-work wire cutters vanished from the shop between six and seven — logged missing by Pratt himself at seven." },
    c3_keylog:    { name: "The Forged Key Log", desc: "Master key to control room and Studio A signed out at 6:15 PM under 'E. Pratt' — in careful, rounded handwriting that is nothing like Pratt's seismograph scrawl." },
    c3_schematic: { name: "The Dog-Eared Page", desc: "The wiring binder cracked open to 'GROUNDING FAULTS — PLATE SUPPLY HAZARDS' — the exact diagram of tonight's trap, thumbed repeatedly by someone who needed to study it. Its author wouldn't." },
    c3_cutters:   { name: "The Hidden Cutters", desc: "Pratt's missing nips, copper-bright from a fresh cut, buried in the thunder crate — a hiding spot only someone who knew no storm was scripted till Easter would trust." },
    c3_dinner:    { name: "The Milt's Diner Alibi", desc: "Iris's diary and the counter man agree: she and Eugene were at Milt's, 6:15–7:05. Both provably out of the building during the trap-setting hour." },
    c3_orchard:   { name: "The Orchard Farm File", desc: "1927: Herrick's broadcast named Ray Lundgren before trial. Life sentence. 1939 wire item: Lundgren dies in prison, innocent to the last. Herrick's red pencil: 'FINALLY.'" },
    c3_letter:    { name: "The 'D.L.' Letter", desc: "1940, kept seven years: 'You did not investigate, Mr. Herrick. You performed. Someday somebody will perform for you. — D.L.'" },
    c3_sponsor:   { name: "The Vellum Cancellation", desc: "The sponsor was pulling out over money. A motive on paper — pointing at a man whose profession is paper." },
    c3_memo:      { name: "The Morrow Termination", desc: "Chet Morrow fired by memo, effective yesterday. 'Nothing personal. Arithmetic.'" },
    c3_visitors:  { name: "The Locked Building", desc: "Doors locked at five, no visitors after 4:40. Six people inside when Herrick died. The killer is in this building, on your list." },
    c3_note:      { name: "The Unfinished Threat", desc: "Chet's abandoned draft: 'You'll regret this, Walter—' Crumpled in his own wastebasket. Loud grief, cold trail." },
    c3_personnel: { name: "The Corrected Name", desc: "Under correction fluid on Dot Lange's 1941 application, the ghost letters rise: LUNDGREN. The daughter has run Herrick's show for six years." },
    c3_boardaccess:{ name: "'Only Me'", desc: "Dot, unprompted: only she could have opened the fatal channel at 12:03. The truth, offered like a shield." },
    c3_neverasked:{ name: "The Question She Didn't Ask", desc: "Shown the forged key log, Dot analyzed the handwriting — and never asked what the key had been used for. Everyone else asked within a minute." },
    c3_admitname: { name: "Dorothy Lundgren", desc: "Confronted with the file, she admits the name and the blood: daughter of the man the 1927 broadcast condemned. Admits nothing more. Waits." },
    c3_expertread:{ name: "The Engineer's Chalk Talk", desc: "Pratt confirms it on the slate: the trap stayed harmless until the board unmuted the studio. The kill required a hand on the board at 12:03." },
    c3_forgery:   { name: "Spikes vs. Curves", desc: "Pratt's real signatures beside the 6:15 entry: a lightning storm against a lullaby. Proven forgery — and the key back on its hook by eight. A tidy, patient, inside hand." },
    c3_student:   { name: "The Apt Pupil", desc: "Six years of Friday-night breakdowns beside Pratt — and last fall Dot borrowed the grounding schematics for a week, 'to understand what she was looking at.'" },
    c3_irisdoubt: { name: "'Never Off the Clock'", desc: "Iris on Dot: the best professional she's known — 'where the clock is doing something for them.' A friend's suspicion, half-swallowed." },
    c3_aircheck:  { name: "The January Aircheck", desc: "Near midnight in January: Dot alone in the dark, replaying the 1927 Lundgren broadcast over and over — timing it with her cue watch." },
    c3_lobbyalibi:{ name: "The Lobby Pair", desc: "Chet and Ostrow in each other's sight in the lobby at 12:03 — two motives, mutually alibied, forty feet from the board." },
    c3_petition:  { name: "The Rotting Petition", desc: "A state re-examination petition on Orchard Farm has sat in a drawer since 1939 — and Chet was shopping it to wire services all week. The old case was already stirring." },
    c3_sixoclock: { name: "Ostrow's Six O'Clock", desc: "At 6 PM, in the emptied building, the sponsor's man saw Dot coming from the shop wing — walking fast, wiping her hands — five hours before her account of the evening begins." },
    c3_confession:{ name: "LANGE'S CONFESSION", desc: "She built the trap in the dinner hour, forged the key log, and sprang it from her own board at 12:03 — sixty seconds of silence for the man who scripted her father's guilt, triggered by his plan to replay it 'proud' as Episode 400." },
  },

  deductions: [
    { id: "d3_board", name: "The Hand on the Board",
      requires: ["c3_patch", "c3_cuesheet", "c3_expertread"],
      text: "The trap was inert until the studio channel opened, and the cue sheet opened it at 12:02:49 sharp — by ritual, by schedule, by the producer's own hand. This murder wasn't committed at six o'clock when the wires were cut. It was committed at 12:03, from the mixing board, by whoever chose to throw that switch. And one person ran the board." },
    { id: "d3_forged", name: "The Dinner-Hour Ghost",
      requires: ["c3_keylog", "c3_dinner", "c3_forgery"],
      text: "The master key was signed out at 6:15 under Eugene Pratt's forged name — while Pratt was provably three blocks away eating meatloaf. The forger wanted the log to hang the engineer. They needed the building empty, the shop open, and an hour alone: the dinner hour, when only one member of staff remained inside." },
    { id: "d3_daughter", name: "Six Years Behind the Glass",
      requires: ["c3_letter", "c3_personnel", "c3_orchard"],
      text: "D.L. — Dorothy Lundgren — warned Herrick in writing in 1940: 'Someday somebody will perform for you.' Then she corrected her name, took the job at his elbow, and produced his show for six years, reading 'FINALLY' in his file every time she dusted the office. This wasn't an impulse. It was a residency." },
    { id: "d3_fuse", name: "Episode 400 Was the Fuse",
      requires: ["c3_script", "c3_aircheck"],
      text: "She had been timing the 1927 broadcast in the dark since January — rehearsing something. Then Herrick scheduled Episode 400: her father's condemnation, replayed 'proud,' with organ music, as an anniversary special. The date of the murder wasn't chosen. It was provoked." },
    { id: "d3_notthem", name: "The Loud Ones Didn't",
      requires: ["c3_lobbyalibi", "c3_petition", "c3_sixoclock"],
      text: "Chet and Ostrow — the two men with motives you could print — sat in each other's sight all night, and Chet's revenge was already in motion on paper. Meanwhile the quietest person in the building was seen at six o'clock coming from the shop wing, wiping her hands, in a station she'd said was closed. The loud hatreds check out. The silent one doesn't." },
  ],

  motiveOptions: [
    { id: "m_contract", label: "The canceled sponsorship money" },
    { id: "m_slot", label: "Revenge for a stolen time-slot" },
    { id: "m_credit", label: "Years of uncredited work on the show" },
    { id: "m_father", label: "Her father, condemned on air and dead in prison" },
    { id: "m_affair", label: "A love affair gone wrong" },
  ],

  solution: {
    culprit: "dot",
    motive: "m_father",
    keyEvidence: ["c3_personnel", "c3_sixoclock", "c3_aircheck", "c3_patch", "c3_cuesheet", "c3_letter", "c3_forgery", "c3_student", "c3_confession"],
    minKeyEvidence: 2,
  },

  epilogues: {
    perfect: [
      "You take her statement at the mixing board, because she asks to give it there, and it runs eleven minutes — timed, you'd swear, to the second. She corrects one of your dates. Her dates are always right.",
      "The Lundgren case is reopened by summer. The 1939 petition comes out of its drawer; two witnesses from 1927 recant on the record; the state vacates the conviction in the fall. Ray Lundgren's name is cleared eight years after his death and one year after his daughter avenged it — which is either justice twice over or justice never, depending which end of the microphone you're standing at.",
      "WQXT gives 'The Midnight Hour' a quiet burial. On the final broadcast, Iris Bell plays the organ alone for the last sixty seconds — not silence after all. She says some rituals shouldn't be inherited.",
      "The DA calls it the cleanest case file he's ever received, and asks who taught you to time a narrative so precisely. You don't tell him: the murderer did. You have never met a better producer.",
    ],
    partial: [
      "You name Dorothy Lange, and you are right — but your case leads with the wrong 'why,' and her lawyer, no fool, nearly makes the trial about everything except 1927.",
      "It is the handwriting that holds: the rounded forgery against Pratt's seismograph, blown up to poster size for the jury. Conviction, second degree. The Orchard Farm case is mentioned only once, in passing, and the petition goes back into its drawer.",
      "She writes you once from the state facility — two lines, cue-sheet neat: 'You had the timeline right and the story wrong, Inspector. My father remains convicted. Somebody should look into that.' You pin it over your desk. Some nights it looks like a taunt. Most nights it looks like an assignment.",
    ],
    wrong: [
      "You make your case against {ACCUSED}, and it holds for exactly nine days — until the handwriting bureau's report lands on your desk. The forged key-log signature matches no one you charged, and matches, with 'high confidence,' the neat rounded hand on six years of WQXT cue sheets.",
      "By then Dorothy Lange has resigned, sold her rooms, and boarded a westbound train, leaving a forwarding address that turns out to be the county cemetery — one plot, one modest stone: RAYMOND LUNDGREN, 1895–1939. The flowers are fresh. They are fresh every month for years, mailed from a different city each time, and no warrant ever finds the sender.",
      "{ACCUSED} is released with apologies, and never again works a full night without the radio on — silence, they tell you, has stopped sounding empty. You know precisely what they mean. It stopped for you at 12:03, March 8th, and it has never started since.",
    ],
    timeout: [
      "At 6:20 the District Attorney arrives, shakes your hand, and takes the file. He owed Walter Herrick favors; the investigation he runs is a eulogy with subpoenas. Verdict: sabotage by 'person or persons unknown,' with dark hints about drifters and a door that was 'perhaps' not locked. It was locked. You checked it yourself at 12:24.",
      "Dorothy Lange produces the station's memorial broadcast. It is, everyone agrees, the finest hour of radio WQXT ever aired — impeccably timed, and closing with sixty seconds of dead air 'for Walter.' Four thousand listeners weep. One producer watches the clock run down, and you will wonder for the rest of your life what her face was doing.",
      "She resigns the following spring and vanishes west. Years later, a small station in another state wins an award for a documentary series re-examining wrongful convictions — produced by a woman the trade papers describe as 'meticulous about timing.' You keep the clipping. It is not evidence. Nothing, now, will ever be evidence.",
    ],
  },
});
