// CASE No. 001 — "The Last Toast of Blackwood Manor"
window.CASES = window.CASES || [];
window.CASES.push({
  id: "blackwood",
  fileNo: "001",
  title: "The Last Toast of Blackwood Manor",
  tagline: "A patriarch, a poisoned vintage, and a house full of good reasons.",
  place: "Blackwood Estate, Verdant Valley",
  date: "October 12th, 1931",
  difficulty: 1,
  startMinutes: 21 * 60 + 40, // 9:40 PM
  timeBudget: 480,            // coroner's wagon returns at 5:40 AM
  deadlineLabel: "The county coroner takes the body — and the case — at 5:40 AM.",
  epigraph: "“A good vintage tells you everything about the year it was born. So does a murder.”",
  briefing: [
    "The call came in at 9:24. Edmund Blackwood — sixty years old tonight, master of the Blackwood vineyards and half the valley besides — raised his birthday glass at 9:12, drank, and was dead before it touched the table.",
    "Sixty guests have been sent home. Five people remain: the young widow, the estranged son, the family physician, the estate sommelier, and the business partner. Each of them poured something into this evening. One of them poured death.",
    "The house doctor is calling it a heart attack. The dark crust at the corner of Edmund's mouth is calling the doctor a liar.",
    "You have until the coroner's wagon returns at dawn. After that, the body, the house, and the truth get signed over to the county — and the county closes cases the easy way.",
  ],
  detectiveNote: "Custom of the house: on his birthday, the master alone drinks from the private Reserve. Everyone at that party knew it. Start there.",

  locations: [
    {
      id: "hall", name: "The Great Hall", col: 2, row: 1,
      desc: "Bunting still hangs over sixty abandoned place settings. Edmund Blackwood lies where he fell, at the head of the long table, one hand still curled as if around a glass. The room smells of candle smoke, roast pheasant, and something faintly, wrongly bitter.",
      hotspots: [
        { id: "h_body", name: "Examine the body",
          found: "Edmund's lips are stained dark, his fingers clawed into his shirtfront. At the corner of his mouth: a thin greenish crust, bitter-smelling. No wound, no struggle. This was not a heart giving out — this was something taken by mouth, and taken tonight.",
          gives: ["c1_body"] },
        { id: "h_table", name: "The toast table",
          found: "Dozens of champagne coupes, all poured from the same magnums — untouched, harmless. But at the head of the table stands one glass apart: heavy crystal, dark red dregs, and at its bottom a fine greenish sediment that smells of cut herbs and bitterness. The master's private glass. Only his.",
          gives: ["c1_glass"] },
        { id: "h_waistcoat", name: "Search Edmund's pockets",
          found: "A gold watch, stopped by the fall at 9:12. A cigar clip. And in the waistcoat pocket, a small brass key engraved E.B. — the kind that fits a desk, not a door.",
          gives: ["c1_key"] },
      ],
    },
    {
      id: "study", name: "The Study", col: 3, row: 1,
      desc: "Edmund's sanctum: leather, ledgers, and a portrait of his first wife Margaret above the cold fireplace. A sideboard by the window holds a crystal decanter, nearly full of dark wine, its stopper set neatly beside it. Dr. Hale sits in the corner armchair, very still, watching you work.",
      hotspots: [
        { id: "h_fireplace", name: "Rake the fireplace grate",
          found: "Among the cold ashes, a page that didn't fully burn — Edmund's hand, a letter drafted and discarded: “…thirty years of friendship will not buy my silence. She deserved the truth then. Tomorrow, at the luncheon, everyone will have it —” The name of the addressee is ash.",
          gives: ["c1_letter"] },
        { id: "h_desk", name: "The locked desk drawer", requiresClue: "c1_key",
          lockedHint: "The center drawer is locked — a small brass keyhole. Edmund would have kept that key close.",
          found: "The brass key turns. Inside: a telegram from the county records office — CONFIRMING YOUR REQUEST RE M. BLACKWOOD DEATH CERTIFICATE AND ATTENDING PHYSICIAN NOTES STOP COPIES ARRIVE TUESDAY — and beneath it, a small diary. Margaret Blackwood's diary. The last entry, six years old: “Marcus has changed my medicine again. I sleep and sleep. Edmund is away and Marcus will let no one else into this room. I am afraid, and I no longer know of what.”",
          gives: ["c1_telegram", "c1_diary"] },
        { id: "h_sideboard", name: "The sideboard and decanter",
          found: "The 1898 Blackwood Reserve, decanted to breathe before the toast. From this decanter, exactly one glass was poured tonight — the master's. When you lift the stopper, under the wine there is that same faint smell: green, herbal, bitter. The poison went into this decanter, in this room, while it stood breathing.",
          gives: ["c1_decanter"] },
      ],
    },
    {
      id: "cellar", name: "The Wine Cellar", col: 1, row: 2,
      desc: "Cold stone and ten thousand sleeping bottles. A single lamp burns over the decanting bench, where Celeste Moreau stands polishing a glass that is already clean, her ledger open beside her.",
      hotspots: [
        { id: "h_ledger", name: "The cellar ledger",
          found: "Immaculate records in Celeste's hand — until the page for the 1898 Reserve bin. Three entries have been razored out and rewritten. The bin should hold five bottles. You count the rewritten line: five. You walk to the bin and count the bottles: five. So why cut the page?",
          gives: ["c1_ledger"] },
        { id: "h_vault", name: "The 1898 Reserve bin",
          found: "Five bottles under thirty years of dust — except the dust lies wrong on three of them, and under your thumb the labels of those three feel new. Fresh glue. Someone replaced three bottles of the most valuable vintage in the valley with fakes, and dressed them in old dust.",
          gives: ["c1_corks"] },
        { id: "h_bench", name: "The decanting bench",
          found: "Celeste's service card, filled out in her precise hand: RESERVE 1898 — DRAWN 7:05 — DECANTED 7:10 — DELIVERED TO STUDY 7:15 — TO HALL FOR TOAST 9:05. The decanter stood alone in the study for nearly two hours. That is your window.",
          gives: ["c1_timeline"] },
      ],
    },
    {
      id: "conservatory", name: "The Conservatory", col: 3, row: 2,
      desc: "Glass walls, night beyond them, and the wet green breath of a hundred plants. Julian Blackwood sits among his dead mother's flowers with a cigarette he isn't smoking.",
      hotspots: [
        { id: "h_foxglove", name: "The foxglove bed",
          found: "Margaret's old foxglove — digitalis, the heart-medicine flower, and in the wrong hands a heart-stopping one. The bed is trampled, stems snapped and bruised. But look closer: snapped, not cut. Nothing was harvested here. Someone blundered through in the dark — or someone wanted it to look like the poison came from this garden.",
          gives: ["c1_foxglove"] },
        { id: "h_settee", name: "The wicker settee",
          found: "Down behind the cushion: a man's cufflink, monogrammed J.B. — and snagged beside it, a long thread of sea-green silk. Vivian Blackwood wore sea-green silk tonight. The cushions are still pressed flat in two places, close together.",
          gives: ["c1_cufflink"] },
      ],
    },
    {
      id: "kitchen", name: "The Kitchen", col: 1, row: 1,
      desc: "Copper pots, the ruins of a birthday feast, and Mrs. Tilly the cook, who has worked this house for thirty years and misses nothing that travels through it.",
      hotspots: [
        { id: "h_dumbwaiter", name: "The dumbwaiter shaft",
          found: "The dumbwaiter runs from the kitchen straight up beside the study chimney. With the hatch open you can hear a floorboard creak two rooms away. Whatever is said in that study, this shaft delivers it downstairs with the soup.",
          gives: ["c1_shaft"] },
        { id: "h_tray", name: "The evening tonic tray",
          found: "On the counter, prepared and never collected: Edmund's nightly heart tonic — glass, spoon, and dropper bottle, laid out on its tray at seven o'clock as always. Mrs. Tilly confirms it: nobody rang for it, and nobody carried it up. The tonic never left this kitchen tonight.",
          gives: ["c1_tray"] },
      ],
    },
    {
      id: "guestwing", name: "The Guest Wing", col: 2, row: 2,
      desc: "A corridor of guest rooms, two of them lived-in tonight: Gordon Pryce's, scattered with business papers and a packed valise — and Dr. Hale's, tidy as a hospital ward, his black medical bag on the bed.",
      hotspots: [
        { id: "h_valise", name: "Gordon's valise",
          found: "Under folded shirts, an envelope of receipts from a San Francisco broker: THREE BOTTLES, BLACKWOOD RESERVE 1898 — SOLD PRIVATE SALE — and a sum large enough to buy a house. Dated six weeks ago. So that's where the real bottles went, and why the cellar ledger bleeds razor cuts.",
          gives: ["c1_receipts"] },
        { id: "h_bag", name: "Dr. Hale's medical bag",
          found: "Ranked vials, folded stethoscope — and a bottle of tincture of digitalis, the heart medicine drawn from foxglove. The pharmacy label is dated three days ago. The bottle is nearly empty. A fresh bottle should last Edmund a month. A lethal dose would empty it in one evening.",
          gives: ["c1_tincture"] },
      ],
    },
  ],

  suspects: [
    {
      id: "vivian", name: "Vivian Blackwood", role: "The widow", age: 34,
      color: "#5d6b42", initials: "VB", location: "hall",
      blurb: "Edmund's second wife of four years. Twenty-six years his junior, beautiful in sea-green silk, and far too composed for a woman widowed an hour ago — or exactly composed enough.",
      topics: [
        { id: "t_v_alibi", label: "Her whereabouts tonight",
          response: "“I was in the hall from seven, playing hostess to sixty people who all wanted a piece of me. I left once — around twenty past eight, to fetch Edmund from his study. He hates— hated to be fetched.” She smooths her skirt. “He told me he'd be along, and he was. That's all.”",
          note: "In the hall all evening; went to the study once, about 8:20, to fetch Edmund." },
        { id: "t_v_marriage", label: "Her marriage",
          response: "“You want to know if I married him for the money. Of course I did — and he knew it, and found it the most honest arrangement of his life. Then four years happened, and I found I'd grown fond of the old tyrant. Nobody warns you about that.” Her voice cracks exactly once, and she hates it.",
          note: "Married for security; claims genuine, complicated fondness." },
        { id: "t_v_study", label: "Who visited the study tonight?", requiresClue: "c1_decanter",
          response: "“The study? Gordon went in around half past seven — for contracts, he said, though he came out looking greyer than he went in. Julian stormed in about twenty to nine and stormed out louder. And when I went to fetch Edmund at 8:20, I passed Dr. Hale coming out — carrying his bag, and grey as candle wax. I remember thinking: the doctor looks worse than the patient.”",
          gives: ["c1_witness"],
          note: "Saw Gordon (7:30), Julian (8:40), and Dr. Hale (leaving at 8:20, bag in hand, ashen) at the study." },
        { id: "t_v_affair", label: "Present the cufflink and silk thread", requiresClue: "c1_cufflink", confront: true,
          response: "She looks at the cufflink a long moment, and the hostess drains out of her. “All right. Julian and I. Since the spring. You may despise me at your leisure, Inspector, but hear this: Julian was with me in the conservatory from a quarter to eight until past eight, and he is not capable of this. Weak men don't poison. They just leave.” She lifts her chin. “And Edmund — Edmund had bigger ghosts than us. He told me last week he intended a reckoning at tomorrow's press luncheon. 'Old accounts set right,' he said. He wasn't talking about the harvest.”",
          gives: ["c1_reckoning"],
          note: "Admits the affair with Julian; alibis him 7:45–8:10. Edmund planned a public 'reckoning' at tomorrow's luncheon." },
        { id: "t_v_hale", label: "About Dr. Hale",
          response: "“Marcus? He's furniture here — thirty years of house calls. He saw Margaret through her last illness, delivered half the valley, holds Edmund's heart in a little brown bottle.” A pause. “Though lately Edmund had gone cold on him. Stopped their chess nights a month ago. When I asked why, he said, 'I'm waiting on a letter.'”",
          note: "Hale is a 30-year fixture; treated the first Mrs. Blackwood. Edmund had recently, quietly frozen him out." },
      ],
    },
    {
      id: "julian", name: "Julian Blackwood", role: "The estranged son", age: 29,
      color: "#47536e", initials: "JB", location: "conservatory",
      blurb: "Edmund's only child, home for the first time in five years and dressed like the money ran out three years ago. Grief and relief are fighting for his face, and neither is winning.",
      topics: [
        { id: "t_j_alibi", label: "His whereabouts tonight",
          response: "“I've been out here most of the night. My mother built this conservatory; it's the only room in this house that doesn't feel like his.” He grinds out the cigarette. “I went in to see him once, before nine. We talked. It didn't go well. It never went well. And now it never will, so you can imagine how I'm enjoying my evening.”",
          note: "In the conservatory most of the evening; admits one bad conversation with his father before nine." },
        { id: "t_j_argument", label: "Present the overheard argument", requiresClue: "c1_argument", confront: true,
          response: "“The cook heard that? Of course she did — this house has ears in the walls.” He laughs without any humor in it. “Fine. I came home to ask for money. Eight thousand dollars of card debts to men who don't send reminder letters. And he said —” Julian's jaw works. “— he said, 'You'll get nothing until you're honest with me.' I thought he knew about— about something else. So I shouted, and I left, and those are the last words we ever said.”",
          note: "Came home to beg for $8,000 in gambling debts. Edmund refused: 'nothing until you're honest with me.'" },
        { id: "t_j_affair", label: "Present the cufflink", requiresClue: "c1_cufflink", confront: true,
          response: "He goes white, then red. “Vivian told you, or you're guessing. Either way — yes. I'm in love with my father's wife, which even I can see is the cheapest melodrama in the valley. When he said 'be honest with me,' I thought he meant her.” He looks at the foxgloves. “I wanted his money, Inspector. I even wanted his wife. I never once wanted him dead. There's a difference, and tonight it's the only thing I've got.”",
          note: "Admits the affair. Believed the 'honesty' his father demanded was about Vivian." },
        { id: "t_j_mother", label: "Present Margaret's diary", requiresClue: "c1_diary", confront: true,
          response: "He reads his mother's last page twice, and his hands are not steady. “She wasn't dying when he took over her care. She was tired, that's all — and then Hale changed her medicines, and she slept, and slept more, and one morning she didn't wake. Heart failure, he wrote. Father was in London the last three weeks of it. Hale kept everyone out of her room — everyone. He said it was for her rest.” He hands the diary back like it's burning him. “Father never forgave himself for being away. I never thought there was anyone else to forgive.”",
          gives: ["c1_sickroom"],
          note: "Margaret declined suddenly under Hale's exclusive care; Hale barred everyone from her sickroom. Edmund was abroad." },
        { id: "t_j_father", label: "About his father",
          response: "“He built all this from forty acres of rocks, and he never let anyone forget the cost — least of all me. Five years ago he told me to come back when I was worth the name. Tonight I came back worth less than when I left.” He shrugs, and it costs him. “He was hard, and he was honest. It's a rare pairing. I only ever managed half of it.”",
          note: "Bitter, broke, and — under all of it — grieving." },
      ],
    },
    {
      id: "hale", name: "Dr. Marcus Hale", role: "The family physician", age: 58,
      color: "#6d5138", initials: "MH", location: "study",
      blurb: "Thirty years the Blackwood family doctor, and Edmund's oldest friend. Silver-haired, steady-handed, professionally sad. He has already written 'cardiac arrest' on the certificate in his mind and is waiting for you to agree.",
      topics: [
        { id: "t_h_alibi", label: "His whereabouts tonight",
          response: "“I arrived at seven, looked in on the study before eight to leave Edmund's evening tonic — his heart wanted watching, especially on a night of excitement — then joined the party. I was twenty feet from him when he fell. I loosened his collar, I felt for a pulse, and I lost my oldest friend under my own hands.” He recites it like a chart. Doctors do. “Is there anything else?”",
          gives: ["c1_haleclaim"],
          note: "CLAIMS he visited the study before 8 to deliver Edmund's evening tonic, then joined the party." },
        { id: "t_h_medical", label: "Cause of death",
          response: "“Cardiac arrest, Inspector. Sixty years old, a rich man's arteries, a long evening, wine and excitement. I had warned him a hundred times.” When you mention the stained lips, the bitter crust, he waves a weary hand. “Red wine and pheasant. You are describing dinner. Leave the medicine to me, and I shall leave the— whatever this is, to you.”",
          note: "Insists it was a heart attack. Dismisses every sign of poison a little too quickly." },
        { id: "t_h_tincture", label: "Present the tincture bottle", requiresClue: "c1_tincture", confront: true,
          response: "“You searched my bag.” The warmth goes out of the room. “That is digitalis, yes — Edmund's own prescription, which I have carried for years. It is nearly empty because it is nearly finished; I refilled it— oh, a month ago at least.” You look at the pharmacy label, dated three days past, and say nothing. Neither does he — but a muscle beneath his eye has begun, very faintly, to keep time.",
          gives: ["c1_halelie"],
          note: "Claims the tincture was refilled 'a month ago.' The pharmacy label says three days. He is lying." },
        { id: "t_h_letter", label: "Present the burned letter", requiresClue: "c1_letter", confront: true,
          response: "He reads the charred page with a face like a closed door. “Edmund wrote many letters he never sent. He had been… unwell in his thinking these past weeks. Suspicious of old friends. Digging up finished griefs.” He hands it back. “Thirty years of friendship, Inspector, does not fit on half a burned page.” You notice he never asks whom the letter was for.",
          note: "Calls Edmund 'unwell in his thinking.' Never asks who the letter addressed — as if he already knows." },
        { id: "t_h_margaret", label: "Ask about Margaret's death", requiresClue: "c1_telegram",
          response: "“Margaret died of heart failure, six years ago, in her own bed, with her own physician in attendance. I signed the certificate myself.” Each word is placed like a surgical instrument. When you mention that Edmund had written to the county for her records, the pause is one beat too long. “Grief invents villains, Inspector. Edmund was sixty, and lonely, and the anniversary was near. I would have talked him out of it.”",
          note: "'I would have talked him out of it' — he knew about the records request before you said a word about its contents." },
        { id: "t_h_break", label: "Lay out the whole of it", requiresDeductions: ["d1_lie", "d1_ghost"], confront: true, climax: true,
          response: "You lay it out: the tonic that never left the kitchen. The tincture bottle three days old and empty. The diary, the telegram, the letter that burned. The question he asked the sommelier about the master's private glass. For a long time the only sound is the fire.\n\n“She was never meant to die,” he says at last, to Margaret's portrait, not to you. “I increased her sedation because she was frightened and wouldn't rest — and I misjudged it, and her heart stopped, and Edmund was in London and I had one hour alone with what I'd done. So I wrote 'heart failure,' and I buried my error with her, and for six years I was the only mourner at that particular grave.”\n\nHe folds his hands, a man at the end of rounds. “Then her diary surfaced, and the records office wrote back, and my oldest friend looked at me across the chessboard like a stranger. He was going to say it aloud, tomorrow, in front of the press. Thirty years of medicine, ended by one sentence. So — the Reserve. His glass and no other's; I made certain of that, at least.” He takes off his spectacles, and he is suddenly very old. “I have carried one accidental death for six years, Inspector. You may now watch me carry a deliberate one considerably less far.”",
          gives: ["c1_confession"],
          note: "CONFESSED. Margaret died of his botched sedation; he falsified the record. Edmund was going to expose him at the luncheon, so Hale poisoned the Reserve." },
      ],
    },
    {
      id: "celeste", name: "Celeste Moreau", role: "The sommelier", age: 41,
      color: "#5e4353", initials: "CM", location: "cellar",
      blurb: "Keeper of the Blackwood cellar for eleven years. Precise as a jeweler, loyal as a hound, and visibly more upset about the violated wine than she is prepared to admit about anything else.",
      topics: [
        { id: "t_c_alibi", label: "Her movements tonight",
          response: "“It is all on my card, Inspector, as it is every year. Drawn at 7:05, decanted at 7:10, delivered to the study at 7:15 to breathe. I carried it to the hall myself at 9:05, and Monsieur Blackwood poured his own glass, as he always did. Between times I was here, below, with the service wines.” She hesitates, first crack in the porcelain. “I poured what killed him. You understand that I will be counting those two hours for the rest of my life.”",
          note: "Her timings match the service card exactly. In the cellar between 7:15 and 9:05." },
        { id: "t_c_tradition", label: "The toast tradition",
          response: "“The custom is older than my service. On the master's birthday, one bottle of the 1898 — his father's first great vintage — is decanted, and the master alone drinks of it. One bottle, one glass, one man. The guests toast him with the ordinary champagne.” She looks at you steadily. “You understand what I am telling you. Poison in that decanter could only ever have reached one mouth in this house. Whoever did this was not gambling.”",
          gives: ["c1_tradition"],
          note: "The Reserve decanter fills exactly one glass: the master's. The poisoner knew their target with certainty." },
        { id: "t_c_asked", label: "Did anyone ask about the toast?", requiresClue: "c1_tradition",
          response: "She begins to say no — then stops. “Dr. Hale. Last Tuesday, in the kitchen garden. He asked whether the master still kept the old custom of the private glass, or whether the Reserve was shared round now. I thought it idle talk, a man making conversation about wine he does not understand.” Her face has gone very still. “It was not idle talk, was it, Inspector.”",
          gives: ["c1_asked"],
          note: "Six days before the murder, Dr. Hale asked her whether the master still drank the Reserve alone." },
        { id: "t_c_ledger", label: "Present the razored ledger", requiresClue: "c1_ledger", confront: true,
          response: "“That is my hand, and my razor, and my shame.” She closes the ledger gently. “Two months ago I found three bottles in the 1898 bin with fresh glue under old dust. Fakes — good ones, but I have eleven years in this cellar. I rewrote the page while I decided what to do, because a ledger that says the master's treasure has been robbed is an accusation, and I did not yet know whom it accused.”",
          note: "She discovered three counterfeit bottles in the Reserve bin two months ago and hid the discrepancy while she investigated." },
        { id: "t_c_fakes", label: "Who swapped the bottles?", requiresClue: "c1_receipts",
          response: "You show her the broker's receipts. She reads them once and her mouth goes thin as wire. “Monsieur Pryce. He has cellar access for 'inventory.' I suspected — I could not prove.” Then, slowly: “Inspector. Understand what this means for your poison. Tonight's bottle was one of the fakes — a decent claret in a dishonest dress. The killer did not poison a legend. He poisoned whatever was in the master's decanter. The bottle never mattered. Only the glass it would fill.”",
          gives: ["c1_counterfeit"],
          note: "Gordon swapped the Reserve bottles for fakes. Tonight's wine was counterfeit — the poisoner cared only whose glass it filled." },
      ],
    },
    {
      id: "gordon", name: "Gordon Pryce", role: "The business partner", age: 55,
      color: "#7a5e2c", initials: "GP", location: "guestwing",
      blurb: "Half of Blackwood & Pryce for twenty years — the half, people say, that counts the money. Sweating through good tailoring, and his valise was packed before you arrived.",
      topics: [
        { id: "t_g_alibi", label: "His movements tonight",
          response: "“I dressed up here until half past seven — I stepped into the study around then, yes, to collect contract copies for the morning, Edmund knew, you may— well.” He remembers you can no longer ask Edmund. “I was in the hall by eight, and there are sixty people to say so. Look, Inspector, I've known that man twenty years. Half my life is in this valley's dirt right next to his.”",
          note: "Admits he was in the study around 7:30 'collecting contracts.' In the hall from eight." },
        { id: "t_g_business", label: "The state of the business",
          response: "“Sound as a bell.” It comes out too fast. “The crash pinched everyone — everyone — but the vineyard is solid. Edmund handled the vines, I handled the ledgers, and the ledgers are fine.” He mops his neck. “Why is it warm in here? It's October.”",
          note: "Claims the firm is sound. Sweating like a man whose ledgers are anything but." },
        { id: "t_g_receipts", label: "Present the broker's receipts", requiresClue: "c1_receipts", confront: true,
          response: "The fight goes out of him all at once, like a dropped marionette. “Margin calls. October '29 didn't pinch me, Inspector, it gutted me — I owed money you can't say out loud. So I borrowed three bottles from a dead man's vanity bin and replaced them with fakes so good even Edmund never— ” He stops. Swallows. “I stole wine. Wine! And here is the joke that will hang me: tonight's bottle was one of my fakes. Forty-dollar claret. Whoever poisoned it wasn't poisoning the '98 — they were poisoning him. That's not my crime. Mine's smaller and shabbier, and I'll confess every ounce of it if it gets your eyes off me for the big one.”",
          gives: ["c1_gordonconfess"],
          note: "Confesses the counterfeit swap — ruined by the Crash, he sold the real bottles. Insists, correctly, that the poisoner targeted the man, not the wine." },
        { id: "t_g_hale", label: "About Dr. Hale", requiresClue: "c1_telegram",
          response: "“Hale? Edmund's shadow. Saintly, sexless, and dull as a wet Sunday.” Then something surfaces. “Though — odd thing. He telephoned the office twice this week. Both times he asked whether Edmund had received 'certain papers' — records, documents, he wouldn't say what. I told him I don't open Edmund's post. He rang off both times without saying goodbye, which for Marcus Hale is practically hysteria.”",
          gives: ["c1_calls"],
          note: "Hale telephoned twice this week, anxious about whether Edmund had received 'certain papers.'" },
      ],
    },
    {
      id: "tilly", name: "Mrs. Tilly", role: "The cook — witness", age: 61, witness: true,
      color: "#545447", initials: "T", location: "kitchen",
      blurb: "Thirty years over the Blackwood stoves. Not a suspect — she was elbow-deep in sixty dinners with three scullery maids for witnesses — but nothing moves through this house without passing her door.",
      topics: [
        { id: "t_t_evening", label: "What she heard tonight",
          response: "“Shouting, sir, up the dumbwaiter shaft — twenty minutes to nine, because the soufflés went in at half past. The master's voice: 'You'll get nothing until you're honest with me!' And young Mr. Julian giving it back with interest, and a door you could hear in the county.” She folds her arms. “Thirty years, and that boy and his father never once said a kind thing quietly or a cruel thing soft.”",
          gives: ["c1_argument"],
          note: "Heard Edmund and Julian's row at 8:40 through the dumbwaiter: 'You'll get nothing until you're honest with me!'" },
        { id: "t_t_margaret", label: "The first Mrs. Blackwood",
          response: "“Ah, Miss Margaret.” The arms unfold; the years land on her. “When she took to her bed, the doctor turned that sickroom into a fortress. Not a soul past the door — not me with her beef tea, not her own boy. 'Rest,' he said, 'complete rest.' Six weeks of complete rest and then a funeral.” She looks at you sharp and old. “I've cooked for sickrooms all my life, sir. I never once met a rest cure that minded who carried the tray.”",
          gives: ["c1_barred"],
          note: "During Margaret's final illness, Hale barred everyone from the sickroom — even the family — for six weeks." },
      ],
    },
  ],

  clues: {
    c1_body:      { name: "The Body", desc: "Dark-stained lips, clawed fingers, a bitter greenish crust at the mouth. Poison, taken tonight — not a failed heart." },
    c1_glass:     { name: "The Master's Glass", desc: "One glass apart from all the rest: the private Reserve glass, with bitter greenish sediment in the dregs. Every other glass in the hall is clean." },
    c1_key:       { name: "Brass Key 'E.B.'", desc: "A small desk key from Edmund's waistcoat pocket. He kept it on his person — whatever it locks, it mattered." },
    c1_letter:    { name: "The Burned Letter", desc: "Edmund's discarded draft: '…thirty years of friendship will not buy my silence. She deserved the truth then. Tomorrow, at the luncheon, everyone will have it—' Addressee burned away." },
    c1_telegram:  { name: "Records Office Telegram", desc: "The county confirms Edmund's request: Margaret Blackwood's death certificate and the attending physician's notes. Copies due Tuesday." },
    c1_diary:     { name: "Margaret's Diary", desc: "Her last entry, six years old: 'Marcus has changed my medicine again. I sleep and sleep… Marcus will let no one else into this room. I am afraid.'" },
    c1_decanter:  { name: "The Reserve Decanter", desc: "Decanted at 7:10, it stood breathing in the study until 9:05 — and beneath the wine, the same bitter herbal smell as the sediment. The poison went in here." },
    c1_ledger:    { name: "The Razored Ledger", desc: "The cellar ledger's 1898 page has been cut out and rewritten in Celeste's own hand. The counts match the bin. So what was corrected?" },
    c1_corks:     { name: "Fresh Glue, Old Dust", desc: "Three of the five 1898 Reserve bottles are counterfeits — new labels dressed in redistributed dust." },
    c1_timeline:  { name: "The Service Card", desc: "Celeste's timings: decanter delivered to the study 7:15, carried to the hall 9:05. Nearly two unwatched hours — the poisoner's window." },
    c1_foxglove:  { name: "The Trampled Foxglove", desc: "Margaret's digitalis bed, crushed and snapped — but nothing cut, nothing harvested. Staged, or blundered through. The poison did not come from this garden." },
    c1_cufflink:  { name: "Cufflink & Silk Thread", desc: "Julian's monogrammed cufflink behind the settee cushion, snagged with sea-green silk — the color Vivian wore tonight." },
    c1_shaft:     { name: "The Dumbwaiter Shaft", desc: "Runs from the kitchen up beside the study. The kitchen hears what the study says." },
    c1_tray:      { name: "The Untouched Tonic Tray", desc: "Edmund's evening heart tonic — prepared at seven, never rung for, never collected. It never left the kitchen tonight." },
    c1_receipts:  { name: "The Broker's Receipts", desc: "In Gordon's valise: private sale of three bottles of 1898 Blackwood Reserve, San Francisco, six weeks ago. A small fortune." },
    c1_tincture:  { name: "The Tincture Bottle", desc: "Digitalis tincture in Hale's bag — pharmacy label dated three days ago, bottle nearly empty. A month's medicine gone in three days. Or in one evening." },
    c1_witness:   { name: "Vivian's Account of the Study", desc: "Study visitors: Gordon at 7:30, Julian at 8:40 — and Dr. Hale, seen leaving at 8:20, bag in hand, grey as candle wax." },
    c1_reckoning: { name: "The Promised Reckoning", desc: "Edmund told Vivian he planned 'a reckoning' at tomorrow's press luncheon. 'Old accounts set right.'" },
    c1_argument:  { name: "The Overheard Row", desc: "8:40 PM, via the dumbwaiter: Edmund to Julian — 'You'll get nothing until you're honest with me!'" },
    c1_sickroom:  { name: "Julian on the Sickroom", desc: "Margaret declined suddenly under Hale's exclusive care. Hale barred everyone from her room. Edmund was abroad and never forgave himself." },
    c1_haleclaim: { name: "Hale's Account", desc: "Hale's own alibi: he went to the study before eight 'to leave Edmund's evening tonic,' then joined the party." },
    c1_halelie:   { name: "The Doctor's Arithmetic", desc: "Hale claims the tincture was refilled a month ago. The label is dated three days past. Doctors do not misread labels." },
    c1_tradition: { name: "One Bottle, One Glass", desc: "The house custom: on the master's birthday the 1898 Reserve is decanted for him alone — one bottle, one glass, one man. Poison in that decanter could only ever reach one mouth." },
    c1_asked:     { name: "Idle Talk, Last Tuesday", desc: "Six days before the murder, Hale asked Celeste whether the master still kept the custom of the private glass." },
    c1_counterfeit:{ name: "The Fake in the Decanter", desc: "Tonight's bottle was one of Gordon's counterfeits. The poisoner wasn't poisoning a legendary vintage — only the one glass it would fill." },
    c1_gordonconfess:{ name: "Gordon's Confession", desc: "Ruined by the Crash, Gordon sold the real Reserve bottles and planted fakes. A thief's confession — offered up to dodge a murderer's noose." },
    c1_calls:     { name: "Two Telephone Calls", desc: "Hale rang the office twice this week, pressing to know whether Edmund had received 'certain papers.'" },
    c1_barred:    { name: "The Fortress Sickroom", desc: "Mrs. Tilly: for Margaret's last six weeks, Hale let no one past the door. 'I never met a rest cure that minded who carried the tray.'" },
    c1_confession:{ name: "HALE'S CONFESSION", desc: "Margaret died of his botched sedation, six years buried under a false certificate. Edmund meant to expose him at the luncheon. So Hale poisoned the one glass in the house that was Edmund's alone." },
  },

  deductions: [
    { id: "d1_target", name: "Poison for One",
      requires: ["c1_glass", "c1_tradition"],
      text: "The sediment was only in the master's private glass, and the Reserve fills no other. The killer wasn't gambling with sixty guests' lives — they knew the house custom, and they aimed at exactly one man." },
    { id: "d1_window", name: "Two Unwatched Hours",
      requires: ["c1_decanter", "c1_timeline"],
      text: "The poison went into the decanter while it breathed in the study, between 7:15 and 9:05. Whoever entered that room in those two hours had their chance. Everyone else is scenery." },
    { id: "d1_lie", name: "The Doctor's Lie",
      requires: ["c1_haleclaim", "c1_tray", "c1_tincture"],
      text: "Hale says he went to the study to deliver a tonic — that never left the kitchen. And his fresh three-day-old tincture of digitalis is nearly empty. He went to that room with a full bottle of heart-stopping medicine and a story he needed to be believed." },
    { id: "d1_ghost", name: "Margaret's Ghost",
      requires: ["c1_letter", "c1_telegram", "c1_diary"],
      text: "The diary, the records request, the burned letter: Edmund believed Margaret's death six years ago was no illness — and he meant to name the man responsible at tomorrow's luncheon. Someone with thirty years of friendship, and everything to lose by morning." },
    { id: "d1_asked", name: "A Question About Glasses",
      requires: ["c1_asked", "c1_glass"],
      text: "Six days before poison appeared in the master's private glass, Dr. Hale asked the sommelier whether the master still drank from it alone. Murderers rehearse. Sometimes, out loud." },
  ],

  motiveOptions: [
    { id: "m_money", label: "For the inheritance" },
    { id: "m_jealousy", label: "Jealousy over Vivian" },
    { id: "m_fraud", label: "To hide the counterfeit-wine fraud" },
    { id: "m_silence", label: "To bury the truth of Margaret's death" },
    { id: "m_debts", label: "To escape crushing debts" },
  ],

  solution: {
    culprit: "hale",
    motive: "m_silence",
    keyEvidence: ["c1_tincture", "c1_halelie", "c1_asked", "c1_tray", "c1_witness", "c1_letter", "c1_telegram", "c1_diary", "c1_confession"],
    minKeyEvidence: 2,
  },

  epilogues: {
    perfect: [
      "You lay the case before the coroner as dawn comes up over the vines: the tonic that never left the kitchen, the emptied three-day-old tincture, the question asked about a single glass six days before it turned bitter — and behind it all, a woman six years dead whose diary finally spoke.",
      "Dr. Marcus Hale does not dispute a word of it. He signs his confession in the same steady hand that signed Margaret Blackwood's false certificate, and asks only that his patients be given fair notice to find another physician.",
      "At the trial, the prosecutor calls it the tidiest case he has ever brought. You know better. There is nothing tidy about a man who buried one accident so deep he had to dig a grave beside it.",
      "The Blackwood Reserve — the real bottles, recovered from a San Francisco broker — is never served again. Julian pours them out among the vines the following spring, for his mother and his father both.",
    ],
    partial: [
      "You name Marcus Hale, and you are right — but the seams of your case show, and his lawyer works every one of them. The motive you offered wobbles; the evidence you led with was not your strongest.",
      "In the end it is the pharmacy label that saves the case: three days, not a month, and twelve jurors who can all read a date. Hale is convicted on the poisoning, though the full truth of Margaret Blackwood never enters the record, and her certificate stands uncorrected.",
      "Justice, of a kind. But walking out past the courthouse steps you can hear the whispers that will follow the family for a generation — every rumor your unfinished case left room for.",
    ],
    wrong: [
      "You make your accusation. {ACCUSED} is taken to the county seat, protesting, and for three days the valley believes you.",
      "On the fourth day the coroner's chemical analysis comes back: digitalis, in quantity — and the pharmacy ledger in town shows Dr. Marcus Hale refilling Edmund Blackwood's tincture three days before the party. By then, Hale's practice is closed, his house is empty, and the morning ferry manifest shows a 'Mr. M. Harlan' traveling light.",
      "{ACCUSED} is released with the county's apologies, which are worth exactly what apologies are worth. The Blackwood file goes into the drawer that every detective keeps and no detective opens. You will not forgive yourself quickly. You should not.",
    ],
    timeout: [
      "The coroner's wagon arrives at 5:40 exactly, and the county takes the body, the house, and the case. The verdict, rendered by men who were never in that study: cardiac arrest, brought on by age and excitement.",
      "Dr. Hale signs the certificate. Of course he does. He has done it before.",
      "Some nights, years later, you will still be in that study, watching the fire, one question from the truth. The dead keep no deadlines. The living are not so lucky.",
    ],
  },
});
