// CASE No. 004 — "The Nine O'Clock Vanishing"
window.CASES = window.CASES || [];
window.CASES.push({
  id: "meridian",
  fileNo: "004",
  title: "The Nine O'Clock Vanishing",
  tagline: "Locked door, sealed window, a voice at half past eight — and a man who'd been dead for an hour.",
  place: "The Meridian Express, Larkspur Pass",
  date: "February 3rd, 1953",
  difficulty: 3,
  startMinutes: 21 * 60 + 45, // 9:45 PM
  timeBudget: 400,            // plows at 4:25 AM
  deadlineLabel: "At 4:25 AM the rotary plows reach the pass and the Meridian rolls — scattering your suspects across three states by breakfast. What you hold at 4:25 is all you will ever hold.",
  epigraph: "“A locked door proves nothing, except that somebody wanted you to stand in the corridor admiring it.”",
  briefing: [
    "Ambrose Keene wrote 'Fair Warning' — sixty-one papers, twenty years, the column that could end a career in a paragraph. What the papers bought was his prose. What certain private citizens bought, at market rates, was his silence: the columns he never ran, filed in red tabs in a wardrobe trunk that travels where he travels.",
    "Tonight he dined early, left the dining car at 7:05, and locked himself into compartment 7 — chain and privacy bolt, his unbroken habit. At 8:12 the Meridian ran her nose into a forty-foot drift at Larkspur Pass and stopped for the night. At 8:30 the porter brought his seltzer, and a voice through the door told him to leave it. At 9:00 the porter knocked again, as ordered. Nothing. At 9:07 they tore the chain out of the frame and found Keene in his armchair with the mark of a broad strap around his throat.",
    "The chain was fastened. The bolt was thrown. The window is sealed under the drift, and the snow around the train lies unbroken. Better still: from half past eight to nine, every passenger on this list can account for every minute. You are being invited, Inspector, to admire a locked door.",
    "You were aboard by luck — off duty, three cars back, the only badge on the mountain. The wire shack can raise the division, but no sheriff reaches the pass before the plows do. The railroad has given you the night. Spend it.",
  ],
  detectiveNote: "Every alibi aboard fits the window from 8:30 to 9:00, snug as a berth. When the alibis fit one window that neatly, ask who built the window.",

  locations: [
    {
      id: "comp7", name: "Compartment 7 — the Locked Room", col: 2, row: 1,
      desc: "The best room on the train and the stillest: green baize, mahogany veneer, the drift pressing gray against the window glass like a hand. Ambrose Keene sits where the mountain found him, in the armchair by the little writing desk, because nobody aboard outranks you and you ordered him left. The corridor door hangs splintered where the conductor's shoulder went through it. The cold is coming up through the floor now that the train only idles for steam.",
      hotspots: [
        { id: "h_body", name: "The dead man in the armchair",
          found: "A big man gone thin inside his suit, the collar loose on a neck it was tailored for. The mark at his throat is a single broad band, two inches wide, with a fine double line of stitching printed into the skin at both edges — not rope, not wire, not hands. A stitched leather strap, drawn once from behind and held. And on the ashtray's rest groove, his cigar: gone out cold at two inches, the ash unbroken along its whole length, his matches beside it unstruck. A man who pays for Havanas relights them. This one was set down within minutes of being lit — and never picked up again.",
          gives: ["c4_strapmark", "c4_cigar"] },
        { id: "h_doorchain", name: "The forced corridor door",
          found: "The chain plate came away whole, all four screws still in it, plaster and oak in the threads — it was seated firm and fastened when the conductor's shoulder hit. The little brass privacy bolt is bent in its keeper, torn through, thrown to the last eighth of an inch. Both engaged from inside; no key works either from the corridor, and the porter will swear no key exists that could. Whoever fastened this door was standing in this room when they did it. The question the room keeps asking you is how they stopped being in it.",
          gives: ["c4_chain"] },
        { id: "h_desk", name: "The writing desk",
          found: "His last column, longhand, the red pencil still lying across it: 'FAIR WARNING — FINAL COLUMN — THE ACCOUNTING. Release Feb. 9. For twenty years this column has sold silence at market rates. Here is the inventory — every name, beginning with my own. And I did not gather these sins alone: the hand that fetched them will be named with the rest.' And on the floor beneath the desk, the ink bottle, thrown clear across the carpet by the 8:12 lurch and shattered — its spray fanned dark across the edge of the blood-settled stain under the chair. The ink sits ON the stain, crisp, unmixed. The blood had already dried when the mountain threw the ink at it.",
          gives: ["c4_accounting", "c4_inkline"] },
        { id: "h_commdoor", name: "The communicating door", requiresClue: "c4_bothrooms",
          lockedHint: "A paneled connecting door to compartment 8, bolt handle thrown on this side — the conductor checked it at 9:07 and moved on. Until you know how these two rooms lived together, the bolt tells you nothing worth twenty minutes.",
          found: "The bolt handle on the 7 side stands at 'fastened' — and turns under one finger, weightless, engaging nothing. You open the door against compartment 8's bolt and look at the edge: the steel tongue has been filed off flush, the stub bright as a new dime, fine gray filings still down in the mortise like frost. This side of the door has been a stage prop for days. Chain the corridor door, throw this dead bolt for the audience, step through into compartment 8, and fasten the real bolt behind you — and compartment 7 locks itself around whatever you leave in the armchair.",
          gives: ["c4_filedbolt"] },
      ],
    },
    {
      id: "corridor8", name: "The Sleeper Corridor & Compartment 8", col: 1, row: 1,
      desc: "A swaying tunnel of mahogany and brass, night-lights turned down to embers, the drift hissing along the windows on the north side. Compartment 8 is the secretary's room, adjoining the dead man's; compartment 6, on the other side, belongs to the nurse. Frances Dell stands in her own doorway with a cardigan over her uniform, not crying anymore, watching you the way people watch a surgeon wash his hands.",
      hotspots: [
        { id: "h_comp8", name: "Compartment 8 itself",
          found: "The secretary's room, tidy as a ledger: typewriter cased, two suits brushed, eleven years of carbon flimsies in banded stacks — 'Fair Warning,' column after column, typed here in this compartment with Keene's red pencil making only the lightest passes over them. The famous voice was drafted twelve feet from where its owner slept. And at the window: the leather lifting strap is gone — cut off at the buckle, the stub's edge showing fresh knife marks, bright and unweathered. Every window on this car has its strap. This one gave its strap up tonight.",
          gives: ["c4_strapstub", "c4_ghostwriter"] },
        { id: "h_jumpseat", name: "The porter's jump seat & the tray",
          found: "The folding seat at the corridor's end commands the whole sleeper — every door from 4 to 9, one unbroken sightline. Poole took the seat at 8:35 after leaving the seltzer, and sat it until his nine o'clock knock; he will swear on thirty years of service that no door along this corridor opened and no soul passed. The tray itself still stands where he set it outside compartment 7 — siphon full, glass dry, ice long melted to a cold puddle. The man who asked for it at 8:30 never opened the door to take it. From 8:35 to 9:00 this corridor was a sealed tube. Whatever happened here was finished before it.",
          gives: ["c4_corridor"] },
      ],
    },
    {
      id: "dining", name: "The Dining Car", col: 3, row: 1,
      desc: "White linen going gray under the low emergency lights, coffee kept alive on a spirit burner, the smell of a dinner service that ended in a mountain. Dr. Eleanor Voss sits very straight at a cleared table with her hands folded, as if visiting hours were a thing she was enforcing on herself. Two tables down, Harold Wexler has spread the wreckage of a working supper — papers, a rye, a smile he keeps checking like a pocket watch.",
      hotspots: [
        { id: "h_steward", name: "The steward's account",
          found: "The dining steward keeps his seatings like scripture. Mr. Keene took the early service alone, ate almost nothing, and left at 7:05; the steward clipped and lit his after-dinner Havana at the vestibule door at 7:07 — 'always at the door, always the one match, twenty runs now.' Mr. Corliss left moments behind him, 'to get the flimsies typed before Summit,' he said. Dr. Voss went forward not long after. The steward's clock is railroad-set, and his memory is better. The cigar in compartment 7 was burning by 7:07 — and dead cold two inches later.",
          gives: ["c4_dinnertimes"] },
        { id: "h_wexlercase", name: "Wexler's briefcase",
          found: "Left gaping while its owner fetched another rye. On top, contracts. Beneath: a Clarion Syndicate wire, decoded and initialed — 'W. — KEENE FINAL COLUMN CANNOT RUN. AUTHORIZE TO $25,000. STOP THE ACCOUNTING AT ANY PRICE.' — and a fresh cashier's draft for that sum, payable to Ambrose Keene, unsigned, undelivered. The syndicate knew what the ninth of February would cost them. They sent a man with a checkbook. The phrase 'at any price' was composed by someone very far from this mountain.",
          gives: ["c4_buyout"] },
        { id: "h_keenetable", name: "Keene's table",
          found: "Still set apart, by the steward's sentiment: one cover, one chair. In the fold of the untouched napkin, where he left it, a flat prescription tin — 'MORPHINE SULPH. ¼ gr. — for Mr. A. Keene — as required for pain.' Half empty. The man who owned sixty-one papers' worth of fear was dining alone on soup he didn't finish and quarter-grain mercies. Whatever was coming for Ambrose Keene, it was coming with or without a strap.",
          gives: ["c4_pilltin"] },
      ],
    },
    {
      id: "lounge", name: "The Observation Lounge", col: 1, row: 2,
      desc: "The rear of the train: club chairs, a shuttered bar, the famous curved window at the tail looking back down a track that isn't there anymore, only snow turning in the dark. Miles Corliss stands at that window with a brandy he isn't drinking, composed as a Sunday supplement. In the deepest chair, Daniel Callahan watches you cross the carpet the way he used to watch referees.",
      hotspots: [
        { id: "h_barchits", name: "The bar chits",
          found: "The lounge steward times his chits — a habit from settling disputes over who drank what since when. Wexler: rye at 7:35, 8:10, 8:50, never out of the room between. Callahan: a whiskey at 7:10, then nothing — he went 'out for air' about 7:25 and wasn't seen again until ten past eight, in a camel coat with the cold still on it. Corliss: nothing all evening until 8:33 — brandy, neat, drunk standing, 'like medicine,' the steward says. The first drink of the secretary's night, thirty seconds after the corridor emptied. Some men drink to a day's end. Some drink to a curtain.",
          gives: ["c4_barchits"] },
        { id: "h_coat", name: "Callahan's camel overcoat", requiresClue: "c4_trunk",
          lockedHint: "A mountain of a coat on the brass hook by the door, still breathing cold. You've no cause to go through a man's pockets — yet. Though somebody went through a dead man's trunk tonight, and this coat has been out in the weather.",
          found: "The inside pocket is stitched deep, and it is carrying a manila file with a red index tab in a dead man's handwriting: 'CALLAHAN, D. — ARENA.' Clippings, affidavits, two photographs of men shaking hands who always denied meeting — the unpublished half of the series that ruined him, the half he's been paying to keep unpublished. The folder's edge is scuffed with fresh brass-bright scratches. It was pried out of a hasp tonight, by somebody who wanted his own life back and didn't care to ask for it.",
          gives: ["c4_stolenfile"] },
      ],
    },
    {
      id: "vestibule", name: "The Porter's Vestibule & Baggage Car", col: 2, row: 2,
      desc: "The working spine of the train: the porter's pantry with its ranked siphons, the shoe rack, the call board — and beyond the swaying gangway, the baggage car, cold as a vault and stacked to the roof lamps with trunks. Elias Poole polishes glasses that are already clean, because thirty years of hands need somewhere to be. He stands straighter than anyone else on this train tonight.",
      hotspots: [
        { id: "h_trunk", name: "Keene's wardrobe trunk",
          found: "A steamer trunk with a lock worth more than the porter's month — and the hasp pried right off it, wood splintered, the fire iron from the baggage rack lying where it was dropped. Inside, the famous red tabs, alphabetical: the bought silence of half a coast. One folder is missing from the C's, and something else sits on top where the thief ignored it: a plain folder of bank drafts, one a month for nine years, made out to a Mrs. Ada Kessler of Dayton, Ohio. No letter, no signature, no claim on her gratitude. Whatever Ambrose Keene was, he was also, secretly and without witnesses, this.",
          gives: ["c4_trunk"] },
        { id: "h_callbook", name: "The porter's call book",
          found: "Standing orders in Poole's copperplate: 'No. 7 — seltzer at 8:30 sharp. No. 7 — knock at 9:00 sharp: Mr. K. has copy to send the moment the section shack opens the line at nine.' The Accounting wasn't waiting for the ninth to leave his hands — the first pages were to go out over the railroad wire tonight, at nine o'clock, from a shack in a snowbound pass. Anyone who wanted that column stopped had until the nine o'clock knock. The dead man's schedule was the murderer's schedule, published in advance.",
          gives: ["c4_nineorder"] },
      ],
    },
    {
      id: "headend", name: "The Head End — Locomotive & Guard's Van", col: 3, row: 2,
      desc: "Out through the vestibule traps into a cold that cancels thought: the big Mountain-class engine idling against the drift she couldn't beat, steam bleeding sideways in the wind, lanterns strung along the flank. The conductor's van smells of coal, oilcloth, and the official version of events. The crew look at your badge like it's the first good news of the night.",
      hotspots: [
        { id: "h_guardlog", name: "The conductor's log",
          found: "Railroad-neat: 'STRUCK DRIFT MP 214.6 — 8:12 PM. All vestibule traps down and locked 8:20. Walked the train 8:40: no damage, snow unbroken both flanks save wind-drift against the north side, all souls counted.' And one more entry, in the brakeman's hand: '7:55 — surprised a party at the trunks in the baggage car, big man, tan coat, made off forward. Believed stowaway. Not found.' The snow says nobody left this train. The brakeman says one of your passengers spent the murder hour at the far end of it, six cars from compartment 7, with a fire iron.",
          gives: ["c4_brakeman"] },
        { id: "h_snowline", name: "The drift below the sleeper windows", requiresClue: "c4_strapstub",
          lockedHint: "A white wall from wheel to window line, wind-packed and climbing. You could dig all night at random and find only February — unless something tells you exactly where to dig.",
          found: "You dig beneath compartment 8's window and eighteen inches down the lantern finds it: a leather window strap, two inches wide, double-stitched at both edges, cut off clean at the buckle end. The stitching matches the mark on Ambrose Keene's throat like a signature matches a check. And the depth tells its own time: the wind has been building this drift only since the train stopped — the strap went out compartment 8's window after 8:12, dropped by somebody standing in that room when the whole train believed the man next door was still alive. The snow that sealed the locked room also caught the weapon coming out of the wrong one.",
          gives: ["c4_strap"] },
      ],
    },
  ],

  suspects: [
    {
      id: "corliss", name: "Miles Corliss", role: "The secretary & legman", age: 41,
      color: "#47536e", initials: "MC", location: "lounge",
      blurb: "Eleven years carrying Keene's dispatch case, typing his columns, booking his compartments — the indispensable man, gray-eyed and pressed at ten at night, quietly arranging your investigation for you. The one person aboard whose living died with Ambrose Keene, which he will point out himself, dryly, before you can.",
      topics: [
        { id: "t_c_account", label: "His account of the evening",
          response: "“I left the diner on his heels at 7:05 — flimsies to type before Summit, or so we both still thought. I was at my machine in eight until the stop threw half my papers on the floor, and after that I gave it up and came back here about half past for a brandy. The first of the day, if the steward's counting, and he counts.” A dry beat. “Between my room and his there's a connecting door, Inspector, bolted both sides — his rule after eight o'clock, and his rules kept me employed. I was twelve feet from him all evening with two thrown bolts between us. You may make of that whatever the door lets you.”",
          note: "Claims: typing in compartment 8 from 7:10 until the 8:12 stop, lounge from about 8:30. Volunteers the communicating door himself — 'bolted both sides, his rule.'" },
        { id: "t_c_keene", label: "Eleven years of Keene",
          response: "“What was he? Sixty-one papers of conscience and one trunk of the other thing, and I kept the diary for both. You want me to say I hated him. I ran his errands for eleven years, Inspector; hate is for men with the time.” He turns the brandy without drinking it. “He was dying — you'll have that from the nurse by now. Dying men rearrange their furniture. He'd begun giving things away: money, mercy, other people's secrets. It made him gentle and it made him careless, and in our trade those are the same disease.”",
          note: "'Dying men rearrange their furniture.' He knew about the illness — and calls Keene's late mercy 'careless,' like a man auditing it." },
        { id: "t_c_ghost", label: "Present the carbon flimsies", requiresClue: "c4_ghostwriter", confront: true,
          response: "He looks at eleven years of his own typing the way other men look at old photographs. “Yes. I wrote it — the sentences, at least; the malice was always genuinely his. He'd talk the column at me over breakfast and I'd make it sound like Ambrose Keene, and by noon he'd forgotten which of us had. Sixty-one papers ran my prose under his name for a decade, Inspector, and the one byline I'll ever get is in your notebook.” The dryness holds, but something under it has gone to wire. “Every legman writes his master's voice. It's the job. You needn't look at me as though it were a skill with only one use.”",
          note: "Admits it flatly: he wrote the column's voice for a decade. Then — unprompted — defends voice-writing as 'a skill with only one use' before you've suggested any use at all." },
        { id: "t_c_strap", label: "Present the strap from the snow", requiresClue: "c4_strap", confront: true,
          response: "He gives the strap one professional glance and hands it back. “A window strap. There are forty on this train and half are cut or missing — souvenir hunters, Inspector; passengers steal anything that unbuckles. If that one came out of the drift below my window, then somebody put it out my window, and I'd remind you my room stood empty and unlocked the whole time I was in this lounge being watched by a steward with a clock.” It is a good answer. It is even a true one, so far as it goes. You notice it accounts carefully for every minute after 8:33, and volunteers nothing at all about the hour before the train stopped.",
          note: "His defense covers 8:33 onward — the fake window — and steps, precisely, around the hour before 8:12. He defends the time nobody has accused yet." },
        { id: "t_c_break", label: "Read him the true timetable", requiresDeductions: ["d4_deadbefore", "d4_falselock"], confront: true, climax: true,
          response: "You give it to him the way he'd have typed it: 7:07, the one match at the vestibule door. 7:45, the grade and the whistle, and a cigar already an hour cold in its groove. 8:12, the mountain throwing ink across blood that had finished drying. The tongue of a bolt filed flush to a bright stub, so a dead man's room could fasten itself behind a living man's exit. The strap off his own window, buried after the stop, under the drift on his own sill. And 8:30 — 'Leave it and get on, porter' — spoken in a voice he had been writing for eleven years, to the one man aboard Ambrose Keene never once called porter. He listens the way he must have listened at a thousand dictations, checking the copy for errors. He finds none, and sets down the brandy, and stops being the indispensable man.\n\n“Three months to live and he got religion on a deadline,” he says, and the dryness is gone; what's under it is younger and much worse. “Twenty years he sold their silence, and I fetched every pound of it — the maids bribed, the letters bought, the photographs, all of it my legwork, his byline, our living. Then the doctors gave him a date, and Ambrose decided to die honest. Honest! At nine o'clock tonight, over a railroad wire, with my name spelled out in the first installment — because you can't confess another man's crimes, Inspector, you can only report them. He'd have gone into the ground absolved, sixty-one papers weeping over the rogue who came clean at the end. And I'd have stood the rest of my life in the open, holding the bag he spent twenty years filling. Absolution for him. The bill to me. It was the last errand he ever tried to hand me, and I declined it.”\n\nHe looks down the dark of the lounge toward the sleeper, and for a moment he is only tired. “I carried his case eleven years. Wrote his voice so long I'd lost the sound of my own — through that door was the only time it was ever mine to use out loud, do you understand that? Three words, and flawless, and wasted on a corridor.” A breath. “You know what caught me. Not the bolt, not the strap. Manners. His. Thirty years of 'Mr. Poole.' I gave that porter everything of Ambrose's I ever learned — the pitch, the growl, the impatience. I never thought to give him the kindness. Eleven years, Inspector, and I didn't know it was there.”",
          gives: ["c4_confession"],
          note: "CONFESSED. Killed Keene at 7:45 with the strap, rigged the filed bolt and the borrowed voice — because 'The Accounting' would have gone out at nine o'clock naming him as the hand that fetched twenty years of sins." },
      ],
    },
    {
      id: "voss", name: "Dr. Eleanor Voss", role: "The surgeon", age: 52,
      color: "#5e4353", initials: "EV", location: "dining",
      blurb: "A thoracic surgeon traveling west to a hospital appointment, who examined the body at 9:12 because she was the nearest thing to a coroner on the mountain. Brisk, exact, and carrying something heavier than her instrument bag — she has been too helpful, too early, in the way of people rehearsing their innocence.",
      topics: [
        { id: "t_v_body", label: "Her examination of the body",
          response: "“I reached him at 9:12. Ligature asphyxia, one application, from behind and above — a strong hand and no hesitation. And I will tell you what I told the conductor, who did not want it: the cooling and the lividity were wrong for a man alive at 8:30. Wrong by an hour, perhaps more; the compartment's warm and I won't perjure myself to a minute. He looked, to my hands, like a man dead since before that train hit the snow.” She holds your eye, level as a scalpel. “They all heard the voice through the door, so they decided the doctor was mistaken. I am not often mistaken, Inspector. I find I am rarely even forgiven for it.”",
          note: "Her medical read, on record since 9:12: dead well before 8:30 — 'like a man dead since before the train hit the snow.' Nobody wanted to hear it, because of the voice." },
        { id: "t_v_evening", label: "Her whereabouts tonight",
          response: "“Early dinner, then my compartment in the forward sleeper — alone, reading, which I'm aware is the alibi of every guilty party in fiction.” A pause with a decision inside it; the decision loses. “I knew him, slightly. By correspondence. Professional matters.” Her folded hands do not move, which is itself a kind of movement. Thirty years of patients have taught her face stillness, and the stillness is working very hard.",
          note: "Alone in the forward sleeper through the real window — unverifiable. Admits knowing Keene 'by correspondence,' and her stillness is doing heavy labor." },
        { id: "t_v_envelope", label: "The porter saw her at his door", requiresClue: "c4_vossvisit", confront: true,
          response: "The stillness ends; what replaces it is almost relief. “Quarterly. For four years. In 1946 a colleague — a friend — died of a morphine overdose, and I signed the certificate as cardiac failure, to spare his family and his name, and Ambrose Keene bought the pharmacy record. You may do the arithmetic on my salary.” She unfolds her hands at last. “At a quarter past seven I knocked on that door to pay in person and ask him, once, to let it end. He wouldn't take the envelope. He said — I'll give it to you exactly — 'Keep it, Doctor. After the ninth there's no debt left to service. Read the papers and then, if you like, forgive me.' I thought it was a new kind of cruelty. It was the last time anyone saw him alive, and I've spent tonight understanding it was mercy, and that somebody killed him inside the half hour for it.”",
          gives: ["c4_refused"],
          note: "7:15: Keene ALIVE, refused her blackmail payment — 'after the ninth there's no debt left to service.' Her secret is a 1946 false certificate; her payment came back with mercy attached." },
        { id: "t_v_keene", label: "What was Keene to her?",
          response: "“For four years, a quarterly hemorrhage and a reason to dread the mail. Tonight?” She takes her time, the way she'd close an incision. “Tonight I examined him. His lungs were a catastrophe — carcinoma, advanced; three months would have been generous, and he'd have known it since autumn, and the tin in his pocket says he was rationing his own relief. A blackmailer dying in more pain than he ever caused, trying to hand the money back on his way out.” She rises to the professional register, where she is safe. “I wanted him ruined, Inspector, at length and in public. I did not want him dead. Dead, I never get to watch him apologize.”",
          note: "Confirms the carcinoma from her own examination — Keene was months from dying and knew it. 'Dead, I never get to watch him apologize.'" },
      ],
    },
    {
      id: "callahan", name: "Daniel 'Big Dan' Callahan", role: "The ruined promoter", age: 54,
      color: "#7a5e2c", initials: "DC", location: "lounge",
      blurb: "Once the biggest fight promoter on the coast, until Keene's 'Arena' series took his license, his partners, and his name — and kept an unpublished second half in a red-tabbed folder, on the installment plan. He boarded this train loudly, told the conductor he had business with Keene, and has been daring you to notice him ever since.",
      topics: [
        { id: "t_k_grudge", label: "His business with Keene",
          response: "“My business with Keene.” He says it like spitting out a tooth. “That man wrote six columns in '49 and I lost the arena, the license, and a partner who'd been at my wedding. Then his errand boy comes around with terms: there's a second half, Danny, and it stays in the trunk for a consideration. Four years I've paid the freight on my own funeral.” He leans forward, and the chair complains. “So I got on his train to have it out, and I'll shake the hand of whoever saved me the trouble. Now ask me the real question, Inspector. You've been circling it like the last sandwich.”",
          note: "Four years of payments to keep the 'Arena' sequel buried — terms delivered by Keene's 'errand boy.' Boarded specifically to have it out with Keene. Wants you to know it." },
        { id: "t_k_night", label: "His whereabouts tonight",
          response: "“The lounge. All evening. Whiskey, cards with nobody, the scenery.” It comes out flat and rehearsed, and he watches you receive it the way he used to watch judges' scorecards. The lounge steward's chits say he was gone from 7:25 to ten past eight — the murder hour, as it happens, though he can't know you know that — and came back wearing the cold. A man who spent thirty years around fixed fights should lie better. Unless the lie is protecting something he wants hidden more than he wants believing.",
          note: "Claims 'the lounge, all evening' — flatly contradicted by the bar chits (out 7:25–8:10, returned cold). Lying, badly, about the real murder window." },
        { id: "t_k_confront", label: "Present the stolen file", requiresClue: "c4_stolenfile", confront: true,
          response: "He goes very red, then very quiet, which on a man his size is worse. “All right. All right. I went back to the baggage car with a fire iron and I took my own life back out of his trunk — forty minutes of splinters and freezing my hands for a folder with my name on it, and your brakeman near caught me at it and I hid behind a coffin crate like a kid stealing apples.” He shoves the folder at you rather than have it taken. “Charge me for the hasp; I'll pay for the hasp singing. But hear this too — that index of his, the C's: there was a fresh gap two folders past mine. Tab stub still in the rail, his own handwriting on it. 'CORLISS, M.' Somebody with the key had been to that trunk before I ever swung the iron — and took the one file the errand boy would want gone.”",
          gives: ["c4_breakin", "c4_emptyslot"],
          note: "CONFESSES the break-in, 7:30–8:10 — six cars from the murder. And in the trunk's index: a fresh gap, tab in Keene's hand — 'CORLISS, M.' The legman's file, already removed by key." },
        { id: "t_k_boarding", label: "What he saw at boarding",
          response: "“One thing, for whatever it buys me. On the platform at Union, Keene's man Corliss was carrying the old man's dispatch case himself — wouldn't give it to the porter, wouldn't set it down, held it like it was ticking. And Keene watched him do it.” Callahan's eyes narrow at the memory. “I promoted fighters thirty years, Inspector. I know what it looks like when a man's cornerman stops meeting his eye. I remember thinking: the champ's got trouble in his own corner. Then I thought about my folder and minded my own business, same as everybody on this train has been doing all their lives.”",
          note: "At boarding: Corliss clutching Keene's dispatch case, 'like it was ticking' — and Keene watching his own man like a fighter watching a cornerman who's stopped meeting his eye." },
      ],
    },
    {
      id: "wexler", name: "Harold Wexler", role: "The syndicate editor", age: 57,
      color: "#6d5138", initials: "HW", location: "dining",
      blurb: "Managing editor of the Clarion Syndicate, twenty years of selling Ambrose Keene to sixty-one papers — aboard, he says, by pure scheduling coincidence. Everything about him is warm, and none of it reaches his eyes, which are doing arithmetic on you the way they've done arithmetic on everything since 1933.",
      topics: [
        { id: "t_w_aboard", label: "Why is he on this train?",
          response: "“Coincidence, is the honest answer — I'm out for the coast bureaus, annual trip, and Ambrose's schedule happened to marry mine. A happy accident.” The smile arrives on schedule. “Of course I looked in on him. One doesn't share a train with the franchise and not buy him a drink. He declined the drink. He was tired, Inspector — my friend was very tired, and I've spent the evening wishing I'd insisted.” It's smooth as fresh newsprint, and like fresh newsprint it comes off on your hands. Editors don't ride two thousand miles for coincidence. They ride for stories, or to stop them.",
          note: "Claims pure coincidence, 'annual trip.' Smooth, warm, and off the shelf. Editors cross the continent to start stories or stop them — never by accident." },
        { id: "t_w_column", label: "The column business",
          response: "“'Fair Warning' is — was — the spine of the syndicate. Sixty-one papers, and forty of them buy the whole package to get it. You're asking what happens to the Clarion without Ambrose Keene.” He turns the rye glass a quarter turn, a man adjusting a headline. “Nothing good, and I'd take it kindly if you'd note that a dead Keene is a catastrophe on my ledger. Whoever did this cost me the franchise of a lifetime. Grief and arithmetic point the same direction for once, Inspector. It's the only comfortable thing about tonight.”",
          note: "Positions himself early: Keene dead is a catastrophe for the syndicate — grief and arithmetic 'point the same direction.' Note he hasn't mentioned the final column exists." },
        { id: "t_w_buyout", label: "Present the syndicate wire", requiresClue: "c4_buyout", confront: true,
          response: "He reads his own decoded wire without expression — an editor reviewing copy he'd hoped was spiked. “All right. The trip wasn't coincidence and you knew it before you sat down. Ambrose sent us the Accounting a week ago — a courtesy, he called it. It names subscribers, publishers, two governors, and the syndicate's own conduct in leaving twenty years of columns unexamined. It is the end of the Clarion, and I was sent with a check to buy the corpse of it. He laughed at me, Inspector. Monday, on the platform, he laughed and said the ninth was coming whether I framed the check or cashed it.” He sets the wire down, and for once the warmth and the eyes agree on something bleak. “So I tried the only other door I could think of. I went to Miles. Told him: talk him down, you're the only one he hears. And Corliss looked past me at the snow and said — I'll hear it the rest of my life — 'The column is handled, Harold.' I took it for reassurance. God help me, I filed it under good news.”",
          gives: ["c4_handled"],
          note: "Admits the mission: sent with $25,000 to kill the Accounting; Keene laughed at him. And Corliss, days ago, looking at the snow: 'The column is handled, Harold.'" },
        { id: "t_w_corliss", label: "About Miles Corliss", requiresClue: "c4_ghostwriter",
          response: "“Miles.” The editor considers, choosing type sizes. “The best legman I ever saw and the most invisible man I ever met — eleven years in that great shadow, and you've found the carbons, so you know whose sentences half of America read with breakfast. I'll give you one thing more, for free. The Christmas dinner, '51: somebody dared Miles to do 'Ambrose ordering his eggs,' and he did it. Not an impression, Inspector — a possession. Eyes shut, you could not tell them apart; the growl, the pauses, the little cruelty in the pauses. The whole table roared. Ambrose laughed too.” Wexler's glass stops turning. “Then he stopped laughing, all at once, the way a man does when he hears his own obituary read in his own voice. And I don't believe Miles ever did it again — where Ambrose could hear.”",
          gives: ["c4_impression"],
          note: "Christmas '51: Corliss's imitation of Keene's voice — 'not an impression, a possession; eyes shut, you could not tell them apart.' Keene stopped laughing first." },
      ],
    },
    {
      id: "frankie", name: "Frances 'Frankie' Dell", role: "The nurse-companion", age: 29,
      color: "#5d6b42", initials: "FD", location: "corridor8",
      blurb: "Hired three months ago, when the diagnosis came — compartment 6, the other side of the dead man's wall. Plain-spoken, steady-handed, and grieving him outright, which makes her the only person on this train who is. What a feared man's nurse knows about him, nobody else alive knows.",
      topics: [
        { id: "t_f_night", label: "Her account of the evening",
          response: "“He sent me to my own supper at seven — 'go eat something that isn't beige, Dell' — and I was back in six by half past. I read; the wall between us is thin, and I've learned his sounds the way you learn a patient's chart. About a quarter to eight, in all that noise on the grade — the whistle going, the whole car pulling — there was one heavy thump through the wall. Like a trunk coming off a rack. I tapped twice — our signal — and got nothing back, and told myself he was asleep. Sick men sleep hard.” Her voice stays level and her hands do not. “I've been arithmetic-ing it all night, Inspector. If I'd knocked at the corridor door instead. If I'd fetched Mr. Poole. A quarter to eight. I was four feet away.”",
          note: "7:45, under the whistle on the grade: one heavy thump through the wall of 7, then no answer to their two-tap signal. She was four feet away, on the other side." },
        { id: "t_f_keene", label: "About Ambrose Keene",
          response: "“I know what he was; he told me himself, second week — laid it all out flat, like a man showing a nurse his worst scar first. Lung carcinoma, spread; doctors in three cities and then he stopped going to doctors. Three months, likely less, and pain he wouldn't take enough morphine for because he wanted his head clear 'for the accounting.'” She looks at the splintered door of 7. “People saw the column. I saw a frightened old man learning kindness at the end the way you'd learn a foreign language — late, with the grammar but not the accent, practicing on whoever was nearest. Mostly that was me and Mr. Poole. I'm not confused about what he was, Inspector. I'm just the only one who met who he was trying to be next.”",
          gives: ["c4_diagnosis"],
          note: "The diagnosis, from the man himself: advanced carcinoma, three months or less — refusing full morphine to keep his head clear 'for the accounting.'" },
        { id: "t_f_amends", label: "What was he planning?",
          response: "“He called it settling the estate, but he meant the other ledger. Letters all January — some with money in them, I posted them myself. Names crossed off a list in his wallet, one at a time, and he'd sleep better each one gone.” She almost smiles. “He told me the column would run the ninth of February and after that, he said, 'the mail gets honest, Dell, and so do I.' He wasn't afraid of dying — he'd made the appointment and meant to keep it looking the whole world in the eye. Somebody didn't rob that man of much, Inspector. Three months. But they robbed him of the one thing he'd stayed alive to do, and I'd like you to weigh that at whatever it weighs.”",
          note: "All January: amends by mail, names crossed off a wallet list one by one. The Accounting was the appointment he was staying alive to keep. The killer stole the confession, not the months." },
        { id: "t_f_onefile", label: "The drafts to Mrs. Kessler", requiresClue: "c4_trunk",
          response: "“You found the Dayton folder, then.” She takes a moment deciding whose secret it is now, and settles on telling it. “Ada Kessler's husband was the first man the column ever ruined — before my time, before the red tabs even. Nine years of drafts and he'd never let me post those; he mailed them himself, every month, no note. He said a note would make it about his conscience instead of her rent.” Then, quietly, because fair is fair: “And since it's a night for opened files — there's no nursing license under Dell, Inspector. There was an incident on a ward once, and a review board, and I've worked under my mother's name since. He knew inside a week; he'd bought the record before I'd unpacked. He never used it. He said everyone alive deserves one file that stays shut, and I was his.” Her eyes finally spill. “That's who you're avenging tonight. Both of them. All three, if you count who he almost got to be.”",
          note: "The Kessler drafts: nine years of unsigned restitution to the first ruined man's widow. And her own secret, freely given — no license under 'Dell'; Keene knew and kept it shut. 'Everyone deserves one file that stays shut.'" },
      ],
    },
    {
      id: "poole", name: "Elias Poole", role: "The porter — witness", age: 61, witness: true,
      color: "#545447", initials: "EP", location: "vestibule",
      blurb: "Thirty years on the Meridian, and the only pair of eyes that covered the sleeper corridor all night. Not a suspect — he was in the dining car pantry with the steward and two waiters when the thump came through the wall, and on his jump seat in six men's view thereafter. What Elias Poole says happened, happened. It's what everyone heard through the door that needs a second look.",
      topics: [
        { id: "t_p_night", label: "The seltzer at 8:30",
          response: "“Mr. Keene's standing order, every night, half past eight to the minute. I knocked and said the seltzer was here, and the voice inside said—” he closes his eyes to carry it exactly, a man who respects testimony, “—'Leave it and get on, porter.' Gruff, low, through the panel. I set the tray down and I went. At nine I knocked for his wire copy, got nothing, knocked again, and fetched Mr. Brennan and we put the door in.” He opens his eyes. “I have said 'so Mr. Keene was alive at 8:30' to the conductor, to the doctor, and to myself, sir. You'll notice I have stopped saying it. Something in that sentence has been sitting wrong with me all night, like a stone in a shoe I can't find.”",
          gives: ["c4_voice"],
          note: "8:30: a gruff voice through the door — 'Leave it and get on, porter.' Poole's own testimony anchors the death window — and Poole himself has stopped believing it, without knowing why." },
        { id: "t_p_rooms", label: "How Keene traveled",
          response: "“Twenty runs now, always the same: compartment 7 for himself, 8 for Mr. Corliss, and the connecting door between them open all day for the business — papers back and forth, dictation, the case. Come eight o'clock Mr. Keene bolts his side, that was the rule; a man's evening is his own, he'd say. Both rooms on one booking, one key, and the key stays with Mr. Corliss.” He aligns a glass on the shelf a quarter inch. “I've made those two rooms up every morning for five years, sir. They're not two rooms. They're one room with a door in the middle of it, and the door minds whoever's holding the key.”",
          gives: ["c4_bothrooms"],
          note: "Keene always booked 7 AND 8 — one booking, connecting door in daily use, ONE key, and the key lives with Corliss. 'One room with a door in the middle of it.'" },
        { id: "t_p_movements", label: "Who moved in the sleeper tonight",
          response: "“Before the stop? Mr. Keene up from dinner just after seven, cigar going. Mr. Corliss behind him, into 8. Miss Dell to her supper and back by half past. And at about a quarter past seven, the lady surgeon — Dr. Voss — knocked at 7 with an envelope in her hand, and Mr. Keene opened to her, and they spoke low, and she went away forward still holding it.” His recall is a timetable. “After the stop I was in the pantry seeing to the lamps till the seltzer, then the jump seat from 8:35, and from that seat, sir, nothing moved in my corridor till nine. I'd give my pension on it. From 8:35, that corridor was mine, and it was empty.”",
          gives: ["c4_vossvisit"],
          note: "7:15: Dr. Voss at Keene's door with an envelope — he opened, alive; she left still holding it. And from 8:35 to 9:00 the corridor was under Poole's eye and empty." },
        { id: "t_p_name", label: "The stone in the shoe", requiresClue: "c4_voice",
          response: "You ask him to say the sentence from behind the door one more time, and watch him find it mid-word. “'Leave it and get on—'” He stops. He sets down the glass and the cloth, and stands very still. “Porter. He said porter.” A long breath. “Thirty years, sir, and Mr. Keene — whatever else that man was, and I know what he was — my first week on his run he asked my name, and it has been 'Mr. Poole' every night since. Every night. Other passengers, I'm 'porter,' I'm 'boy,' I'm 'George.' Never him. Not once in twenty runs.” He looks at you, and his voice goes quiet and completely certain. “Whoever was behind that door at half past eight had Mr. Keene's growl, his words, his impatience — everything a man could learn from the outside of him. But he called me porter, sir. Mr. Keene was the one thing that voice never learned. Mr. Keene was kind to me.”",
          gives: ["c4_wrongname"],
          note: "The stone found: the 8:30 voice said 'porter.' Keene — alone aboard — never once called him that in thirty years. It was 'Mr. Poole,' every night. The voice was a copy, perfect except for the kindness." },
      ],
    },
  ],

  clues: {
    c4_strapmark: { name: "The Strap Mark", desc: "One broad ligature band, two inches, double-stitched edges printed in the skin. A stitched leather strap, drawn once from behind. Not rope, wire, or hands." },
    c4_cigar:     { name: "The Cold Havana", desc: "Lit by the steward at 7:07; found gone out at two inches, ash unbroken, matches unstruck. Set down within minutes of lighting and never touched again." },
    c4_chain:     { name: "The Fastened Door", desc: "Chain and privacy bolt both genuinely engaged from inside when forced at 9:07 — no exterior key exists. Someone fastened this door while standing in the room." },
    c4_accounting:{ name: "'The Accounting'", desc: "Keene's final column, set for Feb. 9: the full inventory of twenty years of bought silence, 'every name, beginning with my own — and the hand that fetched them will be named with the rest.'" },
    c4_inkline:   { name: "Ink Over Dried Blood", desc: "The 8:12 lurch threw the ink bottle across the compartment — its spray lies crisp ON the blood-settled stain, unmixed. The blood had dried before the train ever stopped." },
    c4_filedbolt: { name: "The Filed Bolt", desc: "The communicating door's bolt on the 7 side: handle reads 'fastened,' but the steel tongue is filed off flush — bright stub, filings in the mortise. A stage prop, prepared in advance." },
    c4_strapstub: { name: "The Cut Strap Stub", desc: "Compartment 8's window strap is gone — severed at the buckle, knife marks fresh and bright. The secretary's own window gave up its strap tonight." },
    c4_ghostwriter:{ name: "Eleven Years of Carbons", desc: "Banded flimsies in compartment 8: a decade of 'Fair Warning' typed by Corliss, with only the lightest of Keene's red-pencil passes. The famous voice was drafted by the secretary." },
    c4_corridor:  { name: "The Sealed Corridor", desc: "From the jump seat, Poole watched every sleeper door 8:35–9:00: nothing moved. The seltzer tray untouched. The 'death window' corridor was a sealed tube — whatever happened was over before it." },
    c4_dinnertimes:{ name: "The Steward's Clock", desc: "Keene left dinner 7:05; his cigar clipped and lit at the vestibule door 7:07, railroad time. Corliss followed him out 'to type the flimsies.' Dr. Voss went forward shortly after." },
    c4_buyout:    { name: "The Syndicate Wire", desc: "Clarion to Wexler, decoded: 'KEENE FINAL COLUMN CANNOT RUN. AUTHORIZE TO $25,000. STOP THE ACCOUNTING AT ANY PRICE.' A cashier's draft, undelivered, rides in his briefcase." },
    c4_pilltin:   { name: "The Morphine Tin", desc: "Quarter-grain morphine tablets, prescribed to Keene 'as required for pain,' half gone, left folded in his napkin. The feared man was dining alone on soup and rationed mercy." },
    c4_barchits:  { name: "The Timed Bar Chits", desc: "Wexler: in the lounge 7:35–9:00 without a break. Callahan: gone 7:25–8:10, back wearing the cold. Corliss: nothing all evening until one brandy at 8:33, drunk standing, like medicine." },
    c4_stolenfile:{ name: "The Arena File", desc: "In Callahan's overcoat: his own red-tabbed folder, 'CALLAHAN, D. — ARENA,' pried out of Keene's trunk tonight — the unpublished half of the series he's been paying to bury." },
    c4_trunk:     { name: "The Pried Trunk", desc: "Keene's wardrobe trunk forced with a fire iron: red-tabbed files rifled, one folder gone from the C's — and, ignored on top, nine years of unsigned monthly bank drafts to a widow in Dayton." },
    c4_nineorder: { name: "The Nine O'Clock Order", desc: "Poole's call book: knock at 9:00 sharp — Keene had copy to send the moment the section shack's wire opened at nine. The Accounting was leaving his hands TONIGHT. The killer's deadline, posted in advance." },
    c4_brakeman:  { name: "The Brakeman's Stowaway", desc: "Conductor's log, 7:55: a big man in a tan coat surprised at the trunks in the baggage car, six cars from compartment 7. And the walked flanks at 8:40: snow unbroken — nobody left this train." },
    c4_strap:     { name: "The Strap in the Drift", desc: "Dug from beneath compartment 8's window: a two-inch double-stitched window strap, cut at the buckle, matching the throat mark exactly — and buried at a depth the wind only began building AFTER the 8:12 stop." },
    c4_voice:     { name: "The Voice at 8:30", desc: "Poole's testimony: 'Leave it and get on, porter' — gruff, low, through the panel of compartment 7. The single fact on which every alibi aboard is hung." },
    c4_bothrooms: { name: "One Room, Two Numbers", desc: "Keene always booked 7 and 8 together — connecting door in daily use, bolted only at night, one key to both. And the key lives with Corliss." },
    c4_vossvisit: { name: "The Envelope at 7:15", desc: "Poole saw Dr. Voss knock at compartment 7 about 7:15, envelope in hand. Keene opened the door, alive; she left still holding the envelope. The last confirmed sight of him living." },
    c4_wrongname: { name: "'He Called Me Porter'", desc: "In thirty years, Ambrose Keene never once called Poole anything but 'Mr. Poole.' The flawless voice behind the door got the growl, the words, the impatience — and missed the kindness." },
    c4_refused:   { name: "The Payment Refused", desc: "At 7:15 Keene wouldn't take Voss's money: 'After the ninth there's no debt left to service. Read the papers and then, if you like, forgive me.' The racket was being wound up by its owner." },
    c4_breakin:   { name: "Callahan's Forty Minutes", desc: "He admits it: 7:30–8:10 in the baggage car with a fire iron, prying his own file out of the trunk — the 'stowaway' the brakeman surprised at 7:55, six cars from the murder." },
    c4_emptyslot: { name: "The Missing 'C' Folder", desc: "In the trunk's index, a fresh gap two folders past Callahan's — tab stub in Keene's own hand: 'CORLISS, M.' Removed with a key, before the fire iron ever swung. Keene kept a file on his legman." },
    c4_handled:   { name: "'The Column Is Handled'", desc: "Days ago, Wexler begged Corliss to talk Keene out of the Accounting. Corliss, looking at the snow: 'The column is handled, Harold.' Wexler filed it under good news." },
    c4_impression:{ name: "The Christmas Possession", desc: "Clarion dinner, '51: Corliss did Keene's voice — 'not an impression, a possession; eyes shut, you could not tell them apart.' Keene stopped laughing first, and Corliss never did it again where he could hear." },
    c4_diagnosis: { name: "Three Months, Likely Less", desc: "Advanced lung carcinoma, known to Keene since autumn — confirmed by Voss's examination and by his own flat telling of it to his nurse. He was rationing morphine to keep his head clear 'for the accounting.'" },
    c4_confession:{ name: "CORLISS'S CONFESSION", desc: "He strangled Keene at 7:45 on the grade, locked the room around the body through the filed communicating bolt, and answered the 8:30 knock in the voice he'd written for eleven years — to stop the nine o'clock wire that would have named him." },
  },

  deductions: [
    { id: "d4_deadbefore", name: "Dead Before the Drift",
      requires: ["c4_cigar", "c4_dinnertimes", "c4_inkline"],
      text: "The cigar lit at 7:07 went out untouched at two inches — he stopped being a living man within minutes of sitting down. And when the mountain threw the ink at 8:12, it landed on blood that had already dried. Ambrose Keene was dead the better part of an hour before the voice at 8:30 — which means the voice at 8:30 was not Ambrose Keene, and every alibi on this train is an alibi for the wrong hour." },
    { id: "d4_falselock", name: "The Room That Locked Itself",
      requires: ["c4_chain", "c4_bothrooms", "c4_filedbolt"],
      text: "Chain and bolt were honestly fastened from inside — by the killer, standing over the body. Then out through the communicating door into compartment 8, whose 7-side bolt is a filed sham that reads 'fastened' and holds nothing, and the real bolt thrown from the other side. Compartments 7 and 8 are one room with a door in the middle, and one man holds the key. The locked room was never locked. It was staged — and the stage door opens into the secretary's compartment." },
    { id: "d4_voice", name: "The Borrowed Voice",
      requires: ["c4_voice", "c4_wrongname", "c4_impression"],
      text: "The voice behind the door had Keene's growl, Keene's impatience, Keene's exact register — and called a man 'porter' whom Keene had called 'Mr. Poole' every night for thirty years. There is one person alive who could do Ambrose Keene with his eyes shut so you could not tell them apart, and a room full of Clarion witnesses watched him prove it at Christmas in '51. The imitation was perfect everywhere except the one place Miles Corliss never looked: the kindness." },
    { id: "d4_thief", name: "The Thief at the Far End",
      requires: ["c4_stolenfile", "c4_breakin", "c4_brakeman"],
      text: "Callahan lied about his evening because he spent the true murder hour committing a different crime: 7:30 to 8:10 in the baggage car, six cars from compartment 7, prying his own ruin out of a dead man's trunk — and the brakeman's log catches him there at 7:55, in the middle of the only window that matters. The loudest grudge on the train is guilty of burglary, splinters, and bad lying. Strike Daniel Callahan from the murder." },
    { id: "d4_deadline", name: "The Nine O'Clock Column",
      requires: ["c4_accounting", "c4_nineorder", "c4_emptyslot"],
      text: "The Accounting named every name — 'beginning with my own,' and ending with the hand that fetched twenty years of sins. It was to leave the train over the section-shack wire at nine o'clock tonight; the call book said so in advance. And the one folder lifted from the trunk with a key, before any fire iron swung, was the file marked 'CORLISS, M.' The murder had a deadline, and the deadline was the knock this whole case is named for." },
  ],

  motiveOptions: [
    { id: "m_named", label: "To silence the confession that would name him" },
    { id: "m_syndicate", label: "To kill the column and save the syndicate" },
    { id: "m_arena", label: "Revenge for a ruin printed in sixty-one papers" },
    { id: "m_certificate", label: "To bury an old false certificate for good" },
    { id: "m_mercy", label: "A mercy killing, to spare a dying man the last agony" },
  ],

  solution: {
    culprit: "corliss",
    motive: "m_named",
    keyEvidence: ["c4_confession", "c4_filedbolt", "c4_wrongname", "c4_impression", "c4_inkline", "c4_cigar", "c4_strap", "c4_emptyslot", "c4_handled"],
    minKeyEvidence: 2,
  },

  epilogues: {
    perfect: [
      "You arrest Miles Corliss in the observation lounge at ten past three, and he asks for a moment to knot his tie properly, and gets it. When the plows come through at 4:25 the Meridian rolls down out of the pass with the drift still holding the shape of the strap, and the state police photograph the hole your lantern dug before the thaw can argue.",
      "At trial the prosecution wheels in the actual communicating door, bolt and filed stub, and lets the jury turn the weightless handle themselves, one by one. But it is Elias Poole who convicts him — thirty years of railroad testimony delivered without one wasted word, ending: 'He called me porter, sir. Mr. Keene never did.' The courtroom is silent the way the pass was silent. The jury is out fifty minutes.",
      "On the ninth of February, 'Fair Warning' runs its final column exactly as its author set it — Wexler prints the Accounting entire, names and all, his own syndicate's included, the one brave purchase of his career. Two governors resign. Dr. Voss's name appears in paragraph forty; she has already written to the medical board herself, beating the column to her own confession by six days, and the board, reading both, lets her keep the license. In Dayton, a widow named Ada Kessler learns at last who the drafts were from, and takes the train east to put flowers on a blackmailer's grave.",
      "Frances Dell is not named anywhere, in any paper, ever. There was one file Ambrose Keene kept shut, and you find you have kept it shut too — it isn't evidence, and some ledgers deserve to close balanced. Elias Poole works the Meridian four more winters, and every February third, somewhere on the high line, he sets out a glass of seltzer at half past eight, and nobody tells him to leave it.",
    ],
    partial: [
      "You name Miles Corliss and you are right, but you lead with the wrong ledger, and his lawyer — paid from an account nobody can quite trace — spends the trial waving the syndicate's '$25,000 at any price' wire at the jury until the courtroom smells of reasonable doubt.",
      "The filed bolt and the strap hold him in the end: guilty, second degree, the mountain's own timetable too exact to argue with. But the Accounting never enters the record. The court impounds the red-tabbed trunk, and in the spring an order signed by a judge whose name you later find in paragraph sixty has the contents burned as 'unpublishable defamation of persons unindicted.'",
      "Sixty-one papers run Keene's obituary and not one runs his confession. The silence he spent his last three months trying to give back stays sold, at market rates, forever. You keep your carbon of the final column in the case file, where the rules say evidence lives — and some nights you take it out and read the first line, and put it back, and lock the drawer, and understand him better than you'd like.",
    ],
    wrong: [
      "You make your case against {ACCUSED} at the plow-head with the whole train watching, and it holds long enough for the Meridian to scatter your witnesses across three states by breakfast, exactly as the mountain promised. Miles Corliss handles the arrangements for the body. He is very good at arrangements.",
      "In April a section gang clearing the spring melt at Larkspur Pass turns up a leather window strap, two inches wide, double-stitched, cut at the buckle, eighteen inches under where compartment 8 stood — and by the time the report crawls up through the division offices, 'Fair Warning' has resumed in sixty-one papers, 'edited from the notes of Ambrose Keene by Miles Corliss.' The columns are gentler now. And around the country, quietly, certain monthly payments have resumed — to a new post-office box.",
      "{ACCUSED} is released with the railroad's apologies and yours, and never takes a sleeper again. Neither, in honesty, do you — or rather, you take them, but you no longer sleep on them. You lie in the berth listening to the connecting doors breathe in their frames, and every one of them, all night, in every state, is a voice saying 'Leave it and get on, porter,' perfectly, except for the kindness.",
    ],
    timeout: [
      "At 4:25 the rotary plows come through in a storm of white and lantern light, and the Meridian rolls. By breakfast your suspects are across three state lines; by Friday the case belongs to four jurisdictions and therefore to none; by spring it is a railroad legend with the details wrong. Verdict: person or persons unknown, in a room the reports still call locked.",
      "The Accounting never runs. Wexler retires with a syndicate intact and a look men bring back from wars. The red-tabbed trunk is released to the estate — which is to say, to its executor of record, Miles Corliss, who signs for it with the dead man's own fountain pen and carries it to the taxi himself, like something ticking.",
      "Years on, you hear a radio tribute to the late great Ambrose Keene, voiced by 'a longtime associate.' The growl is perfect: the pauses, the impatience, the little cruelty in the pauses. Four thousand listeners hear a dead man live again. You hear a corridor on a snowbound mountain, and a glass of seltzer nobody drank, and you switch it off before the kindness has a chance not to be there.",
    ],
  },
});
