// CASE No. 002 — "The Final Bow"
window.CASES = window.CASES || [];
window.CASES.push({
  id: "orpheum",
  fileNo: "002",
  title: "The Final Bow",
  tagline: "The dagger was a prop for two hundred performances. Tonight it wasn't.",
  place: "The Orpheum Theatre, Bay City",
  date: "November 21st, 1936",
  difficulty: 2,
  startMinutes: 22 * 60 + 5, // 10:05 PM
  timeBudget: 420,           // cast walks at 5:05 AM
  deadlineLabel: "At 5:05 AM the union lawyer arrives and the company walks. Whatever you have by then is the case.",
  epigraph: "“Theatre is the art of making an audience believe a lie. Someone in this building is very good at their job.”",
  briefing: [
    "Closing night of 'The Scarlet Hour' — two hundred and eleven performances, and in every one of them, the actor Roland Pierce stabs Lillian Vane with a trick dagger whose blade folds into the handle. Two hundred and ten times, she stood up for her curtain call.",
    "At 9:48 tonight, in front of eight hundred witnesses, the blade did not fold. Lillian Vane died at center stage, in character, to applause. It took the audience a full minute to understand they were no longer watching a play.",
    "Someone swapped the prop for a real dagger — someone who could walk backstage without a single head turning. The doors were watched all night. Your murderer took a bow with the rest of them.",
    "The company is being held in the building. The union lawyer arrives at five. Curtain's up, Inspector.",
  ],
  detectiveNote: "Everyone backstage handles the lie for a living. Don't listen to the performances — check the props, the paper, and the timing.",

  locations: [
    {
      id: "stage", name: "The Stage", col: 2, row: 1,
      desc: "The set of 'The Scarlet Hour,' still dressed for Act III: a Parisian garret, a painted moon. A chalk line where Lillian Vane finished her two hundred and eleventh performance. Victor Delacroix, the playwright, stands in the wings giving his statement to a sergeant — again — in a voice built to reach the back row.",
      hotspots: [
        { id: "h_dagger", name: "The murder weapon",
          found: "A real dagger, no theatre piece: heavy, honed, with a maker's stamp at the ricasso — 'B. & K. CUTLERS' — and on the grip, the ghost of a gummed paper label, scraped away. Pawnshops label their stock with gummed paper. This blade was bought, recently, from somewhere that sells things no one asks about.",
          gives: ["c2_dagger"] },
        { id: "h_mark", name: "Where she fell",
          found: "The chalk line, and beside it a property basket overturned in the confusion. Under it, folded small and tight as if snatched at: a page in Lillian's handwriting — her planned curtain speech. '…tonight, at our final bow, I must speak a name you will not find in your programme: the true author of The Scarlet Hour, who died penniless while another man—' The bottom half is torn away. Torn, not cut. Somebody grabbed for this page and got only half.",
          gives: ["c2_speech"] },
        { id: "h_trap", name: "The stage trapdoor",
          found: "The Act II trapdoor, bolted from below since intermission per the stage manager's rules. The bolt is thrown — but the dust on the ladder beneath is smeared by a single fresh handprint. Someone stood on this ladder tonight, head level with the stage floor, close enough to hear every cue.",
          gives: ["c2_trap"] },
      ],
    },
    {
      id: "wings", name: "The Wings & Prop Table", col: 1, row: 1,
      desc: "The working dark of the theatre: rope, sandbags, the great prop table laid out in taped and labeled squares. Mabel Finch, the property mistress, stands guard over it like a widow at a grave. A boy of about fourteen — Pip, the callboy — sits on a hamper, hugging his knees.",
      hotspots: [
        { id: "h_proplog", name: "The prop table log",
          found: "Every prop, checked and initialed before each act. Act III, tonight: 'DAGGER — CHECKED 9:30 — M.F.' But look at the ink: every other entry on the page is fountain-pen blue-black. This one is pencil, written over an erasure, and pressed hard. A record that was made after it mattered.",
          gives: ["c2_log"] },
        { id: "h_firebucket", name: "The fire bucket",
          found: "Regulation sand bucket by the fly rail. Under three inches of sand: the trick dagger — the real prop, blade folding sweet as ever, sand in its hinge. The swap is confirmed. The killer buried the lie's twin ten feet from the stage and trusted no one to look in the one bucket nobody ever touches.",
          gives: ["c2_propdagger"] },
        { id: "h_callboard", name: "The call board",
          found: "Chalked calls for the evening: HALF — 7:25. ACT I — 8:00. INTERVAL — 9:12 TO 9:32. ACT III BEGINNERS — 9:40. The interval is your window: twenty minutes when the stage went dark, the prop table stood unwatched, and everyone in the building had somewhere to be and no one confirming they were there.",
          gives: ["c2_interval"] },
      ],
    },
    {
      id: "dressing", name: "Lillian's Dressing Room", col: 1, row: 2,
      desc: "Star's quarters: mirrors ringed in hot bulbs, two hundred telegrams of congratulation, roses going brown. The room has been searched by someone in a hurry — drawers not quite shut, the travel trunk's tray askew. Searched before you got here.",
      hotspots: [
        { id: "h_vanity", name: "The vanity drawer",
          found: "Beneath the greasepaint, a bundle of letters tied in faded ribbon, postmarked 1929 to 1931, signed 'Your Tom.' Love letters — and working letters: '…finished the second act of our Scarlet Hour tonight, your scenes and mine braided so close I no longer know whose lines are whose. When it is staged, my darling, it will be both our names above the title or neither.' Tom. The programme in the lobby says 'by Victor Delacroix.'",
          gives: ["c2_letters"] },
        { id: "h_trunk", name: "The travel trunk",
          found: "Under the costumes, a keepsake: a cheap playbill from a valley repertory house, summer 1931 — 'THE CRIMSON HOUR, a new play by THOMAS ABEL & LILLIAN VANE' — with a strip pasted across it: CANCELED. And folded inside, a newspaper cutting from that same August: 'Playwright Thomas Abel, 31, dies of fever at County Hospital; theatrical hopes unrealized.' Five years later, 'The Scarlet Hour' opened in Bay City. By Victor Delacroix.",
          gives: ["c2_playbill"] },
        { id: "h_door", name: "The ransacked room itself",
          found: "Whoever searched here knew what they wanted: papers. The telegrams are untouched, the jewel case unopened — but every drawer that could hold a letter has been gone through, and the blotter on her writing desk shows a torn corner still clamped under the bar. The killer wanted her words, not her valuables. And they didn't find all of them.",
          gives: ["c2_ransack"] },
      ],
    },
    {
      id: "greenroom", name: "The Green Room", col: 2, row: 2,
      desc: "Sagging sofas, a tea urn, and the two people who shared the stage with Lillian Vane when she died: Roland Pierce, still in costume, staring at his own hands — and Adele Winters, the understudy, who has cried her stage makeup into a Greek mask.",
      hotspots: [
        { id: "h_teaurn", name: "The notice board",
          found: "Pinned above the tea urn: the closing notice, posted a month ago — and next to it, yesterday's addition in the director's hand: 'TRANSFER TO NEW YORK UNDER DISCUSSION. COMPANY WILL BE ADVISED.' A Broadway transfer. Every career in this building was riding on the next two weeks, and on the star saying yes.",
          gives: ["c2_transfer"] },
        { id: "h_knitting", name: "Adele's knitting bag",
          found: "Wool, needles, a dog-eared script of the Marguerite role annotated in two hundred performances of hope — and a telegram, dated this morning: 'MY DARLING GIRL — PATIENCE — YOUR CHANCE WILL COME WHEN HEAVEN WILLS IT — MOTHER.' Tonight of all nights, heaven obliged. The kind of coincidence juries hate and detectives should distrust in both directions.",
          gives: ["c2_telegramA"] },
      ],
    },
    {
      id: "office", name: "The Director's Office", col: 3, row: 2,
      desc: "Hugo Braff's lair above the box office: posters of past triumphs, a bottle of rye at low tide, and a telephone that has clearly been shouted into recently. Braff himself fills the desk chair like a man defending it.",
      hotspots: [
        { id: "h_deskdrawer", name: "The desk drawer",
          found: "An insurance policy on the production, with a rider naming the principal performers — payable on 'death or incapacity ending the run.' Premiums current. And beneath it, three letters from the Marberry Club, each politer and more frightening than the last, regarding Mr. Braff's outstanding obligations: four thousand dollars, due in full, 'before the new year, one way or the other.'",
          gives: ["c2_insurance", "c2_debts"] },
        { id: "h_phonepad", name: "The telephone pad",
          found: "The top sheet is torn off, but a pencil rubbing raises the impression: 'MAJESTIC HOTEL — MISS VANE'S SUITE — 7:40.' Braff telephoned Lillian's hotel before the show. Under it, half a sentence pressed deep as anger: 'last chance to sign before—'",
          gives: ["c2_phonecall"] },
      ],
    },
    {
      id: "box", name: "Box C — the Author's Box", col: 3, row: 1,
      desc: "Victor Delacroix's private box, velvet and gilt, with the best view in the house of the play he signs. His coat is over the chair, his opera glasses on the rail, his satchel beneath the seat. He himself is down on the stage, performing his grief for the sergeant.",
      hotspots: [
        { id: "h_satchel", name: "The leather satchel",
          found: "Drafts of 'The Scarlet Hour' — and beneath them, an older manuscript on yellowed paper, water-stained, in a cramped hand that is not Victor's: 'THE CRIMSON HOUR, by Thomas Abel.' Scene for scene, speech for speech, it is the play that made Delacroix famous — with Victor's confident blue pencil rewriting names and trimming lines directly over a dead man's ink.",
          gives: ["c2_manuscript"] },
        { id: "h_ashtray", name: "The ashtray on the rail",
          found: "One cigar, and a half-burned fold of notepaper in a woman's hand. What survives: '…two hundred performances of his words in my mouth, Victor. Pay what his family is owed — every dollar, publicly — or at the final bow I say his name to eight hundred people. You have until closing night. — L.' He burned it in his own box, watching the play. It didn't burn enough.",
          gives: ["c2_ultimatum"] },
        { id: "h_glasses", name: "The opera glasses",
          found: "Fine German glasses — focused, when you raise them, not on center stage where his star performed, but down and to the left. On the wings. On the prop table. The author of the evening watched his best scene from the best seat in the house.",
          gives: ["c2_glasses"] },
      ],
    },
  ],

  suspects: [
    {
      id: "roland", name: "Roland Pierce", role: "The leading man", age: 38,
      color: "#47536e", initials: "RP", location: "greenroom",
      blurb: "The matinee idol whose hand held the dagger. Still in costume, still stained, being ruined in real time. Either the most wronged man in Bay City or the boldest murderer in it — he did it in front of eight hundred people, after all.",
      topics: [
        { id: "t_r_account", label: "The moment it happened",
          response: "“I've done that stab two hundred and eleven times. You drive for the breastbone and the blade folds — it must fold, it's checked every night. Tonight it went in and my hand knew before my head did. The weight was wrong. The sound was wrong.” His voice is a ruin of its stage self. “She looked at me. She knew I didn't know. That's what I'll keep, Inspector — she spent her last second on my innocence.”",
          note: "Insists the weight was wrong the instant he struck. Two hundred and eleven performances of muscle memory as his witness." },
        { id: "t_r_interval", label: "His whereabouts at the interval",
          response: "“In my dressing room, resting the voice — alone, which I'm told is the wrong answer. My dresser brought tea at… half past nine? He'll say so.” A hollow laugh. “Twenty years on the stage and my alibi is a boy with a teapot.”",
          note: "Alone in his dressing room over the interval; only his dresser's 9:30 tea to vouch for him." },
        { id: "t_r_lillian", label: "About Lillian",
          response: "“I asked her to marry me in June. She said no — kindly, which was worse. She said—” he frowns, retrieving it exactly, “—'I'm spoken for, Roland. He's been dead five years and I'm still spoken for.' I thought it was a beautiful line. I even wondered which play it was from.” He looks up. “It wasn't from a play, was it.”",
          gives: ["c2_spoken"],
          note: "Proposed in June; refused. 'He's been dead five years and I'm still spoken for.' A grief she kept — and a motive he'd carry, if you believe he's acting." },
        { id: "t_r_dagger", label: "Present the real dagger", requiresClue: "c2_dagger", confront: true,
          response: "He will not touch it. “That's not ours. Ours lives on the prop table in a taped square like everything Mabel governs, and it has a nick on the pommel where I dropped it in Boston.” He makes himself look at the blade. “Whoever put that in the square knew it would pass. It's the same length, same blackened hilt. Someone measured our lie, Inspector, and had a real one made to fit.”",
          note: "Confirms the substitute was matched to the prop — same length, same blackened hilt. The swap was prepared, not improvised." },
        { id: "t_r_speech", label: "The curtain speech", requiresClue: "c2_speech",
          response: "“She told me there'd be a speech tonight — 'a debt paid, long overdue.' I assumed she meant thanking the company.” He reads the torn half-page and his jaw goes tight. “The true author. Two hundred and eleven performances. Inspector, I have spoken that part until it's in my bones — and I'll tell you something for nothing: Act II is better than anything else Victor Delacroix ever wrote. We used to joke about it in the company. 'Whose ghost wrote the good act?' We joked.”",
          note: "The company privately joked that Act II was beyond Delacroix's talent. 'Whose ghost wrote the good act?'" },
      ],
    },
    {
      id: "adele", name: "Adele Winters", role: "The understudy", age: 27,
      color: "#5e4353", initials: "AW", location: "greenroom",
      blurb: "Two hundred and eleven performances in the wings, word-perfect in a role she never got to play. Tomorrow's papers will call her the luckiest woman in Bay City, in the way that ends careers before they start.",
      topics: [
        { id: "t_a_interval", label: "Her whereabouts at the interval",
          response: "“By the stage door, crying, if you want the truth of it. Closing night does that to understudies — two hundred and eleven times I dressed for a part I never played, and tonight was the last time and I let myself grieve it. Pip saw me. Little pitchers see everything in this building.” She twists her handkerchief. “Then Lillian died and I thought — God forgive me, for one half of one second I thought: now. You may hang me for the half-second, Inspector. It's the only thing I'm guilty of.”",
          note: "At the stage door through the interval, crying — seen by Pip the callboy. Confesses the half-second of terrible hope, unprompted." },
        { id: "t_a_lillian", label: "About Lillian",
          response: "“Everyone expects the understudy to hate the star. Lillian made it impossible. She ran lines with me on Sundays — her Sundays, Inspector. She said, 'Learn it as yours, not as mine; the theatre is cruel and someday it will hand you my part cruelly.'” The handkerchief stops. “I used to think that was just her way of talking. Actresses foreshadow. But she said it in September like she meant it. Like she knew this run would end badly.”",
          gives: ["c2_foreknew"],
          note: "In September, Lillian began preparing Adele 'as if she knew the run would end badly.' The star sensed danger weeks ago." },
        { id: "t_a_telegram", label: "Present her mother's telegram", requiresClue: "c2_telegramA", confront: true,
          response: "She reads it and goes scarlet, then — unexpectedly — laughs, one awful hiccuping sob of a laugh. “Mother sends that telegram every closing night. Every one, for six years, four companies. 'Your chance will come when heaven wills it.' There's a biscuit tin at my lodgings with thirty of them, and you're welcome to warrant it open.” Her eyes harden, first steel you've seen in her. “Check the tin, Inspector. Then find who really willed it, because heaven didn't.”",
          note: "The 'ominous' telegram is a six-year closing-night ritual — a biscuit tin of identical ones at her lodgings, checkable. Red herring, retired." },
        { id: "t_a_company", label: "Backstage gossip",
          response: "“What the wings knew? Mr. Braff owes money to the Marberry Club — the dressers price his watch weekly and it keeps getting cheaper. Mabel skipped her Act III prop check tonight; she was up in the office having a royal row with Braff about the wages he owes her — you could hear it through the floor. And Lillian and Mr. Delacroix had gone poisonous since September. Contract talk, we all assumed.” She hesitates. “Though once, in the dark of the wings, I heard her say to him: 'You can pay in money or you can pay in truth, Victor. Those are the only currencies I take now.'”",
          gives: ["c2_gossip"],
          note: "Mabel SKIPPED the 9:30 prop check (rowing with Braff over wages). And Lillian to Victor, overheard: 'Pay in money or pay in truth.'" },
      ],
    },
    {
      id: "braff", name: "Hugo Braff", role: "The director", age: 52,
      color: "#7a5e2c", initials: "HB", location: "office",
      blurb: "Director, producer, and owner of the Orpheum's debts. A big man in a checked suit, sweating brandy and arithmetic. The insurance policy in his drawer is worth more than his season.",
      topics: [
        { id: "t_b_interval", label: "His whereabouts at the interval",
          response: "“Up here, on the telephone to New York — the Shubert people, about the transfer. You may confirm it with the exchange; the call lasted the whole damned interval and cost me eleven dollars and my remaining dignity.” He rubs his face. “Twenty minutes of begging, Inspector, with the door shut. That's my alibi. Begging.”",
          gives: ["c2_braffcall"],
          note: "On a long-distance call to New York for the entire interval — verifiable with the telephone exchange. Door shut, but the line was live." },
        { id: "t_b_insurance", label: "Present the insurance policy", requiresClue: "c2_insurance", confront: true,
          response: "“Yes, I insured the run. Every producer insures the run! You insure against your star breaking an ankle, not—” he can't say it. He pours rye instead. “Here's what your policy doesn't tell you. Dead stars void transfers. The Shuberts wanted 'The Scarlet Hour' WITH Lillian Vane; without her I've got scenery and debts. That policy pays four thousand. The transfer was worth forty. I'm the one man in this building who needed her breathing, Inspector — I was losing money every minute she was dead before she was even cold.”",
          note: "The policy pays $4,000; the New York transfer needed Lillian alive and was worth ten times that. Her death ruins him — it doesn't rescue him." },
        { id: "t_b_phonecall", label: "Present the phone pad rubbing", requiresClue: "c2_phonecall", confront: true,
          response: "“I called her hotel at 7:40, yes. 'Last chance to sign before New York' — the transfer contract. She'd been stalling for weeks and closing night was the deadline.” He empties the glass. “You know what she said? She said, 'I'll sign tomorrow, Hugo. After tonight there's a thing I must do at the curtain, and after it's done, the play may not be worth transferring.' I thought she was being theatrical. Lillian was never theatrical, Inspector. Off the stage, that woman never wasted a word in her life.”",
          gives: ["c2_stalling"],
          note: "Lillian, at 7:40: she'd sign AFTER the curtain speech — 'after it's done, the play may not be worth transferring.' She knew the speech would detonate the property." },
        { id: "t_b_mabel", label: "The row with Mabel", requiresClue: "c2_gossip",
          response: "He winces. “She came up at the interval about her back wages — three weeks owed, and she's right, and I shouted at her because she's right. Nine-fifteen to half past, the pair of us going at it through my telephone call; the Shubert man heard her and asked if that was the play.” Then it lands on him, slow and cold. “Half past. Mabel checks the props at half past. If she was up here shouting at me—” He sits down heavily. “Then nobody checked the dagger. My God. I gave the killer the window myself, over three weeks' wages.”",
          note: "Confirms Mabel was in his office 9:15–9:30 — corroborated by the Shubert man on the phone. The 9:30 prop check never happened; the log is a lie." },
      ],
    },
    {
      id: "mabel", name: "Mabel Finch", role: "The property mistress", age: 49,
      color: "#5d6b42", initials: "MF", location: "wings",
      blurb: "Twenty-two years running prop tables, and nothing crosses hers without her initials. Her table is her scripture — which is what makes the pencil entry in tonight's log a kind of blasphemy.",
      topics: [
        { id: "t_m_table", label: "The prop table rules",
          response: "“Every piece lives in a taped square, checked before every act, initialed. The dagger's mine to check because it's the piece that touches an actress's ribs eight times a week — I test the fold against my own palm.” She says it like a catechism. Then, quieter: “Twenty-two years, Inspector. Ask me tonight's question. I can see you carrying it.”",
          note: "Her check includes testing the trick blade's fold against her own palm. Had she checked it at 9:30, the swap could not have survived." },
        { id: "t_m_log", label: "Present the penciled log entry", requiresClue: "c2_log", confront: true,
          response: "The porcelain cracks all at once. “I skipped it. Twenty-two years and I skipped the one check that ever mattered — I was up in that office fighting for three weeks' wages while somebody salted my table. I came down at 9:35, the squares looked right, the curtain was called, and I—” her hands are shaking, “—I penciled the entry after they carried her off. Because I couldn't bear the log to say what I'd done. Arrest me for the forgery, Inspector. I'll thank you for it. But the swap was made between 9:12 and 9:35, on my table, in my dark — and I want whoever used my absence more than you do.”",
          gives: ["c2_window"],
          note: "CONFESSES the forged entry. The check never happened; the swap window is the interval, 9:12–9:35. Her rage at the killer reads true." },
        { id: "t_m_dagger", label: "Present the real dagger", requiresClue: "c2_dagger", confront: true,
          response: "She examines it like a jeweler. “Stage-blackened hilt — but blackened with stove polish, fresh; smell it. Weighted like ours, cut down to our length. Somebody had our prop's measurements.” She looks up sharply. “And there's one place those measurements live: the property plot, typed, in the production book. Three copies. Mine, Mr. Braff's — and the author's. Mr. Delacroix asked for his in September. Said he was 'documenting the production for posterity.' First interest in props that man has shown in two hundred performances.”",
          gives: ["c2_plot"],
          note: "The fake was built to the prop's documented measurements. The property plot exists in three copies — and Delacroix requested his in September." },
        { id: "t_m_who", label: "Who came near the table tonight?",
          response: "“Before the interval? Nobody but my own hands. During it—” bitterness, “—I wasn't there, so ask the boy. Pip sits the hamper by the rail all night; it's his post. That child has watched two hundred and eleven performances from the same yard of darkness. Whatever crossed my table at the interval, Pip's eyes crossed it too.”",
          note: "Pip the callboy sat by the rail through the interval. Whatever happened at the prop table, the boy saw." },
      ],
    },
    {
      id: "victor", name: "Victor Delacroix", role: "The playwright", age: 44,
      color: "#6d5138", initials: "VD", location: "stage",
      blurb: "The celebrated author of 'The Scarlet Hour' — five years famous, impeccably grieved, quoting his own eulogy for tomorrow's papers. His signature is on the play, the programme, and, you begin to suspect, considerably less of the writing.",
      topics: [
        { id: "t_v_grief", label: "His account of the evening",
          response: "“I watched from my box, as I have every closing night of my career. One writes the play; then one is condemned to watch other people live in it.” The phrases arrive pre-polished. “When the blade struck true I thought — forgive me — I thought Roland had found some new sincerity. Then the house understood, all eight hundred at once. Inspector, I have written that sound my whole life and never heard it before. I shall never write again.” He will, and you both know it.",
          note: "Watched from Box C. His grief is fluent, structured, and quotable — a performance with drafts behind it." },
        { id: "t_v_interval", label: "His whereabouts at the interval",
          response: "“The author's box, with a cigar. I may have stretched my legs in the corridor.” When you mention the backstage pass door beside Box C, he waves it away. “I am the author; I go where my play is. Perhaps I stepped through for a glass of water at the wings — the evening is a blur of grief, Inspector, one doesn't log one's footsteps.” Backstage. He's admitted it — carelessly, or because he knows the boy saw him.",
          gives: ["c2_victorback"],
          note: "Admits — vaguely — to stepping backstage at the interval 'for a glass of water.' The author's box connects to the wings by the pass door." },
        { id: "t_v_authorship", label: "Present the manuscript and letters", requiresClue: "c2_manuscript", requiresClueAlso: "c2_letters", confront: true,
          response: "For the first time, the sentences stop arriving. “Tom Abel was my friend. We shared a table at the repertory; when he died I— preserved his work. Edited it. Completed it. Collaboration is the theatre's oldest—” He stops, because you are holding the title page where his blue pencil strikes out a dead man's name. The mask doesn't slip; it changes, which is worse. “Prove ink, Inspector. Manuscripts are undated. The dead don't hold copyrights, and Bay City remembers who's famous.” Cold to the bone. “Was there anything else?”",
          note: "Confronted with the theft, he does not deny it — he lawyers it. 'Manuscripts are undated. The dead don't hold copyrights.'" },
        { id: "t_v_ultimatum", label: "Present the burned ultimatum", requiresClue: "c2_ultimatum", confront: true,
          response: "“Lillian was given to dramatics in her correspondence—” “She was never theatrical,” you say, in Braff's words, and watch it hit. He recovers in a breath, but you saw the floor move. “She wanted money for Abel's people. I'd have paid it. I'd have paid twice over — money is the cheapest thing in this building.” His voice drops, almost honest for one sentence: “What she wanted couldn't be bought. She wanted his name said aloud. In my theatre. Over my play.” He remembers himself. “And now, tragically, the question is moot.”",
          note: "'What she wanted couldn't be bought. She wanted his name said aloud.' The motive, in his own voice — one sentence before the mask came back." },
        { id: "t_v_break", label: "Play the final scene for him", requiresDeductions: ["d2_swap", "d2_theft"], confront: true, climax: true,
          response: "You set it out in order, like blocking a scene: the property plot he requested in September. The dagger cut to its measurements, bought from a pawnshop counter. The pass door from Box C. The callboy who watched him stand at the prop table at 9:21 with his hands where the taped squares are. The opera glasses focused not on his star, but on the table — watching, all through Act III, to see whether his one real scene would play.\n\n“Two hundred and eleven performances,” he says finally, and his voice has changed — flatter, quicker, a writer talking shop at last. “Do you know what it is to take a bow, every night, for a dead man's play? To be embraced for the second act? Critics would say — to my face, smiling — 'Delacroix, you've never matched it since.' Of course I hadn't. HE wrote it. I stole a corpse's coat, Inspector, and it fit, and for five years I have been cold inside it every single night.”\n\nHe looks at the chalk mark, center stage. “She gave me until the final bow. She'd have done it — she never wasted words. So I wrote the ending the only way it couldn't be rewritten.” A long exhale, almost relief. “Tom gets his name back now, I suppose. The dead don't hold copyrights. But God, how they collect.”",
          gives: ["c2_confession"],
          note: "CONFESSED. He swapped the dagger at the interval to stop the curtain speech that would have named Thomas Abel as the true author." },
      ],
    },
    {
      id: "pip", name: "Pip", role: "The callboy — witness", age: 14, witness: true,
      color: "#545447", initials: "P", location: "wings",
      blurb: "Fourteen, all elbows and stage-fright, posted on the hamper by the fly rail every night of the run. Not a suspect — six stagehands had him in sight striking Act II furniture through the interval. But the wings are his kingdom, and nothing crosses them unseen.",
      topics: [
        { id: "t_p_interval", label: "What he saw at the interval",
          response: "He talks to his boots, but he talks. “Miss Winters was at the stage door crying — she does, closing nights, it's not my business to say. Mrs. Finch went up to the office and there was shouting after. And…” the boots get a long study, “…Mr. Delacroix came through the pass door. About twenty past nine. Stood at the prop table. I thought — he's the author, he's allowed, it's his play, isn't it? He had his glass of water in one hand.” A pause you could drive a truck through. “His other hand I couldn't see. He stood between me and the table, sir. Like he knew where I sat.”",
          gives: ["c2_pip"],
          note: "9:21 PM: Delacroix came through the pass door and stood at the prop table — body positioned between Pip and the taped squares." },
        { id: "t_p_more", label: "Anything else, any night", requiresClue: "c2_pip",
          response: "“One thing. A fortnight back, after notes, Mr. Delacroix asked me where old props go — 'when a piece is retired, boy, where does it live?' I told him the loft. He asked what happens to a piece nobody would miss.” The boots again. “Then last Tuesday I fetched his coat from the box and there was a parcel under it, long, in brown paper, and he took it from me quick and said it was books. It wasn't heavy like books, sir. I carry his books. I know what his books weigh.”",
          gives: ["c2_parcel"],
          note: "A fortnight ago Delacroix asked where retired props go. Last Tuesday: a long brown-paper parcel in his box, 'books' — the wrong weight for books." },
      ],
    },
  ],

  clues: {
    c2_dagger:    { name: "The Real Dagger", desc: "B. & K. Cutlers' mark, a scraped-off gummed label — pawnshop stock, bought recently, cut and blackened to pass for the prop." },
    c2_speech:    { name: "The Torn Curtain Speech", desc: "Lillian's planned final-bow speech: she meant to name 'the true author of The Scarlet Hour.' The bottom half was torn away by a grabbing hand." },
    c2_trap:      { name: "The Trapdoor Handprint", desc: "One fresh handprint on the under-stage ladder — someone stood head-level with the stage tonight, in the dark, listening to cues." },
    c2_log:       { name: "The Penciled Log Entry", desc: "'DAGGER — CHECKED 9:30 — M.F.' — in pencil, over an erasure, on a page of fountain pen. A record written after the fact." },
    c2_propdagger:{ name: "The Trick Dagger", desc: "The true prop, buried in the fire bucket's sand ten feet from the stage. The swap is fact, and it happened in the building." },
    c2_interval:  { name: "The Interval Window", desc: "Call board: interval 9:12–9:32. Twenty minutes of dark, empty stage and unwatched prop table." },
    c2_letters:   { name: "Letters from 'Tom'", desc: "1929–31, signed 'Your Tom': he and Lillian wrote a play together — 'our Scarlet Hour… both our names above the title or neither.'" },
    c2_playbill:  { name: "The 1931 Playbill", desc: "'THE CRIMSON HOUR by Thomas Abel & Lillian Vane' — canceled. And Abel's obituary, that same August. Five years later Delacroix's 'Scarlet Hour' opened." },
    c2_ransack:   { name: "The Searched Dressing Room", desc: "Someone went through Lillian's room for papers — letters, not valuables — and left a torn corner under the blotter. They didn't find everything." },
    c2_transfer:  { name: "The Broadway Transfer", desc: "Posted yesterday: New York transfer under discussion. Every career in the building was riding on the next fortnight." },
    c2_telegramA: { name: "Adele's Telegram", desc: "'Your chance will come when heaven wills it — Mother.' Sent the morning of the murder. (And, it turns out, every closing night for six years.)" },
    c2_insurance: { name: "The Insurance Policy", desc: "Production insurance paying on the death of a principal performer. Premiums current, payable to Hugo Braff." },
    c2_debts:     { name: "The Marberry Club Letters", desc: "Braff owes the Marberry Club four thousand dollars, 'due before the new year, one way or the other.'" },
    c2_phonecall: { name: "The Phone Pad Rubbing", desc: "Braff called Lillian's hotel at 7:40: 'last chance to sign before—'. The director was pressing his star hours before she died." },
    c2_manuscript:{ name: "Thomas Abel's Manuscript", desc: "The original 'Crimson Hour' in a dead man's hand — with Victor's blue pencil striking out Abel's name and trimming his lines." },
    c2_ultimatum: { name: "The Burned Ultimatum", desc: "Lillian to Victor: pay Abel's family publicly, 'or at the final bow I say his name to eight hundred people. You have until closing night.'" },
    c2_glasses:   { name: "The Opera Glasses", desc: "Delacroix's glasses, left focused not on center stage but on the wings — on the prop table. He watched his mechanism, not his star." },
    c2_spoken:    { name: "'I'm Spoken For'", desc: "Lillian refused Roland in June: 'He's been dead five years and I'm still spoken for.' Her heart was in an August 1931 grave." },
    c2_foreknew:  { name: "The September Change", desc: "From September, Lillian drilled Adele in the role 'as if she knew the run would end badly.' She sensed the danger she was courting." },
    c2_gossip:    { name: "The Wings Know Everything", desc: "Mabel skipped the 9:30 check (rowing over wages). And Lillian to Victor, in the dark: 'Pay in money or pay in truth. Those are the only currencies I take now.'" },
    c2_braffcall: { name: "The New York Call", desc: "Braff spent the entire interval on a verifiable long-distance call to the Shubert office — with Mabel shouting at him through half of it." },
    c2_stalling:  { name: "'After It's Done'", desc: "Lillian to Braff at 7:40: she'd sign the transfer only after the curtain speech — 'after it's done, the play may not be worth transferring.'" },
    c2_window:    { name: "The Unwatched Table", desc: "Mabel's confession: no 9:30 check occurred. The swap window is the interval, 9:12–9:35 — exactly when the table stood in the dark." },
    c2_plot:      { name: "The Property Plot", desc: "The prop's exact measurements exist in three typed copies. Delacroix requested his in September — his first interest in props in two hundred performances." },
    c2_victorback:{ name: "A Glass of Water", desc: "Delacroix admits stepping backstage at the interval through the Box C pass door — 'for a glass of water at the wings.'" },
    c2_pip:       { name: "Pip's Testimony", desc: "9:21 PM: Delacroix stood at the prop table, water glass in one hand, his body placed between the boy and the taped squares." },
    c2_parcel:    { name: "The Brown-Paper Parcel", desc: "Last Tuesday: a long parcel in Delacroix's box — 'books,' he said, taking it quickly. The wrong weight for books. The boy carries his books." },
    c2_confession:{ name: "DELACROIX'S CONFESSION", desc: "He stole a dead friend's play and lived famous inside it for five years. Lillian gave him until the final bow to confess. He rewrote the ending instead." },
  },

  deductions: [
    { id: "d2_swap", name: "The Twenty-Minute Murder",
      requires: ["c2_propdagger", "c2_window", "c2_interval"],
      text: "The trick dagger went into the fire bucket and the real one onto the table during the interval, 9:12–9:35 — the one stretch of the night the prop table stood unwatched. The killer knew Mabel's check would not happen, or gambled on the dark, and either way they were backstage in that window." },
    { id: "d2_theft", name: "A Dead Man's Play",
      requires: ["c2_letters", "c2_playbill", "c2_manuscript"],
      text: "'The Scarlet Hour' is Thomas Abel's 'Crimson Hour,' stolen whole after his death in 1931 — and Lillian Vane, his co-author and his love, was the one living person who could prove it. Five years of fame were built on her silence." },
    { id: "d2_countdown", name: "The Final Bow Deadline",
      requires: ["c2_speech", "c2_ultimatum"],
      text: "Lillian set the terms in writing: restitution to Abel's family, or she names him from the stage at the final bow. Tonight WAS the deadline. The murder didn't happen on closing night by chance — closing night was the fuse." },
    { id: "d2_author", name: "The Author at the Table",
      requires: ["c2_pip", "c2_plot", "c2_dagger"],
      text: "A blade cut to the prop's documented measurements. The property plot Delacroix requested in September. And the boy who watched him stand over the taped squares at 9:21, body angled to block the view. The author was at the prop table, in the window, with the means in reach." },
    { id: "d2_ruin", name: "The Man Who Needed Her Alive",
      requires: ["c2_braffcall", "c2_insurance", "c2_stalling"],
      text: "Braff's policy pays four thousand; the transfer she was about to sign was worth ten times that, and only with Lillian in it. His whole interval sits on a verifiable long-distance line. The director is ruined by this death, not rescued — strike him from the list." },
  ],

  motiveOptions: [
    { id: "m_insurance", label: "The insurance money" },
    { id: "m_role", label: "To finally claim the leading role" },
    { id: "m_rejection", label: "A rejected suitor's revenge" },
    { id: "m_plagiarism", label: "To keep the theft of a dead man's play buried" },
    { id: "m_wages", label: "Rage over debts and unpaid wages" },
  ],

  solution: {
    culprit: "victor",
    motive: "m_plagiarism",
    keyEvidence: ["c2_manuscript", "c2_ultimatum", "c2_pip", "c2_plot", "c2_speech", "c2_parcel", "c2_letters", "c2_playbill", "c2_confession"],
    minKeyEvidence: 2,
  },

  epilogues: {
    perfect: [
      "You arrest Victor Delacroix at center stage, on the chalk mark, which even he seems to recognize as the correct blocking. The pawnbroker identifies him by Thursday; the parcel, the property plot, and the boy's testimony do the rest.",
      "At trial, the prosecution reads Thomas Abel's second act aloud, in full, into the record. The courtroom is silent the way theatres are silent. It is the largest audience Abel's own words have ever been credited to, and his sister weeps in the gallery — not, she says afterward, for the verdict.",
      "The Scarlet Hour reopens in the spring under its true title and true name, with Adele Winters as Marguerite. On opening night there are two hundred and twelve seats sold in the name of Lillian Vane, all of them empty, all of them paid for by the company.",
      "Roland Pierce sends you a single line on hotel stationery: 'She spent her last second on my innocence. Thank you for spending your night on it.'",
    ],
    partial: [
      "You name Victor Delacroix, and he retains the best lawyers a stolen fortune buys. The case holds — the boy is steady on the stand, and pawnbrokers have long memories — but the motive you led with lets the defense muddy what should have been clear water.",
      "He is convicted of the murder; the theft of the play never enters the record. 'The Scarlet Hour, by Victor Delacroix' stands in every library catalogue, and Thomas Abel remains a fever statistic from 1931.",
      "Lillian Vane died to say one name aloud. The man who killed her will die in prison — but the name goes unsaid, and some nights that arithmetic keeps you at your desk long after the bottle says go home.",
    ],
    wrong: [
      "You make your case against {ACCUSED}, and Bay City's papers convict them by morning — 'BACKSTAGE FIEND CAUGHT.' The company disbands. The theatre goes dark.",
      "Three weeks later a pawnbroker on Dock Street, reading old news over his counter, recognizes a photograph: the celebrated Victor Delacroix, who bought a dagger for cash in October and asked to have the blade cut down. By the time the wire reaches you, Delacroix has sailed for the Continent — 'gathering material,' his statement says, 'for a new play.'",
      "{ACCUSED} is released to a ruined career and your written apology. The Abel manuscript never surfaces. Somewhere in Europe, a famous man is beginning act one of something new, and you know exactly whose desk drawer he'll take it from.",
    ],
    timeout: [
      "At 5:05 the union lawyer arrives with writs, and the company scatters into the Bay City fog. An open verdict: person or persons unknown.",
      "The Orpheum never reopens. They say the ghost light burns on the stage of every dark theatre so the ghosts can find their marks. The Orpheum's burns over a chalk line that was never answered for.",
      "Victor Delacroix's next play opens in London to warm reviews. Critics note a new theme in his work: 'the corrosive weight,' one writes, 'of an unconfessed act.' He has finally, you reflect, begun writing from life.",
    ],
  },
});
